import { readFileSync } from "node:fs";
import { describe, it, expect } from "vitest";
import {
  registry,
  isSub,
  allDepts,
  deptEnabled,
  activeDepts,
  findDept,
  allSections,
  findSection,
  parentOf,
  settingsDef,
  usedBy,
  groupedFields,
  fieldsFilledCount,
  connectionIdsFor,
  connectionsConnectedCount,
  parseSectionRoute,
  sectionHref,
  buildProfilePatch,
  buildConnectionsPatch,
  buildDepartmentsPatch,
  buildCustomConnectionsPatch,
  buildCentrePatch,
  applyPatchToDraft,
  businessTypeLabel,
  draftFromProfile,
  type ClientCentreRegistry,
  type CentreDraft,
  type CentreProfile,
} from "./clientCentre";

// ── Registry parity ──────────────────────────────────────────────────────────────────────────────
// `clientCentreRegistry.json` (this package) must be byte-identical to platform-nest's
// `src/modules/clients/centre/registry.json` — both are generated by the SAME script
// (`scripts/cmc/extract-registry.cjs`) from the gitignored CMC snapshot, and the plan calls the
// nest copy "the single source". Same relative-path precedent as `rbac-capability-parity.test.ts`
// reading platform-nest files from platform-ui's test tree.
// `new URL(literal, import.meta.url)` is intercepted by Vite's static asset-URL transform when the
// path is a string LITERAL in the call — it rewrites the expression to a dev-server `http://` asset
// path instead of leaving it as a runtime file:// URL, and `readFileSync` then refuses it ("The URL
// must be of scheme file"). Routing the path through a variable (as `rbac-capability-parity.test.ts`
// already does) is not just style here — it is what keeps this a real filesystem read.
function readFileAt(relativePath: string): string {
  return readFileSync(new URL(relativePath, import.meta.url), "utf8");
}

describe("registry parity with platform-nest", () => {
  it("is byte-identical to the nest copy", () => {
    const nestRaw = readFileAt("../../../platform-nest/src/modules/clients/centre/registry.json");
    const uiRaw = readFileAt("./clientCentreRegistry.json");
    expect(uiRaw).toBe(nestRaw);
  });
});

describe("registry basics", () => {
  it("has 28 section settings entries and a registry version", () => {
    expect(registry.version).toBeGreaterThanOrEqual(1);
    expect(Object.keys(registry.sectionSettings)).toHaveLength(28);
  });
});

describe("isSub", () => {
  it("distinguishes a leaf page from a sub-section", () => {
    expect(isSub({ name: "Booking Reports" })).toBe(false);
    expect(isSub({ id: "mk_strat", name: "Strategy & Planning", pages: [] })).toBe(true);
  });
});

describe("allDepts / deptEnabled / activeDepts", () => {
  it("prepends the industry module for a business type that has one", () => {
    const depts = allDepts(registry, "hotel");
    expect(depts[0].id).toBe("ix");
    expect(depts.slice(1)).toEqual(registry.departments);
  });
  it("has no industry module for a business type without one (other)", () => {
    expect(allDepts(registry, "other")).toEqual(registry.departments);
  });
  it("a department not overridden and not in defaultOff is enabled", () => {
    expect(deptEnabled(registry, "hotel", {}, "rs")).toBe(true);
  });
  it("an explicit override wins over the default-off list either way", () => {
    expect(deptEnabled(registry, "hotel", { rs: false }, "rs")).toBe(false);
    // Force a business type/department combination that is default-off, if one exists, else assert
    // the override-on path directly.
    expect(deptEnabled(registry, "hotel", { it: true }, "it")).toBe(true);
  });
  it("activeDepts filters allDepts by deptEnabled", () => {
    const active = activeDepts(registry, "hotel", { rs: false });
    expect(active.find((d) => d.id === "rs")).toBeUndefined();
    expect(active.find((d) => d.id === "ix")).toBeDefined();
  });
  it("findDept locates a department by id, including the industry module", () => {
    expect(findDept(registry, "hotel", "ix")?.name).toBe("Hotel Operations");
    expect(findDept(registry, "hotel", "mk")?.name).toBe("Marketing");
    expect(findDept(registry, "other", "ix")).toBeUndefined();
  });
});

describe("allSections / findSection / parentOf", () => {
  it("includes every sub-section alongside its parent department", () => {
    const sections = allSections(registry, "hotel");
    const ids = sections.map((s) => s.id);
    expect(ids).toContain("mk");
    expect(ids).toContain("se"); // SEO sub-section nested under Marketing
    expect(ids).toContain("mk_strat");
    // No duplicates, no double-count of the industry module.
    expect(new Set(ids).size).toBe(ids.length);
  });
  it("finds a sub-section by id directly, without needing its parent", () => {
    expect(findSection(registry, "hotel", "se")?.name).toBe("SEO, AEO & GEO");
  });
  it("parentOf resolves a sub-section's owning department, and is idempotent on a top-level id", () => {
    expect(parentOf(registry, "hotel", "se")?.id).toBe("mk");
    expect(parentOf(registry, "hotel", "mk_strat")?.id).toBe("mk");
    expect(parentOf(registry, "hotel", "mk")?.id).toBe("mk");
  });
});

describe("settingsDef / usedBy / groupedFields", () => {
  it("returns the fields/connections list for a section, empty for an unknown one", () => {
    const rs = findDept(registry, "hotel", "rs")!;
    expect(settingsDef(registry, rs).fields.length).toBeGreaterThan(0);
    expect(settingsDef(registry, { id: "nope", name: "x", pages: [] })).toEqual({ fields: [], connections: [] });
  });
  it("usedBy lists every OTHER section sharing a field, excluding the current one", () => {
    // `trading` (Trading name / brand) is used by rs (Reservations) among others.
    const others = usedBy(registry, "hotel", "fields", "trading", "rs");
    expect(others).not.toContain("Reservations");
    expect(others.length).toBeGreaterThan(0);
  });
  it("groupedFields orders keys by fieldGroups' display order and drops unknown keys", () => {
    const grouped = groupedFields(registry, ["trading", "unknown-key-xyz", "legal"]);
    // Both `trading` and `legal` are Identity-group fields — same group, one bucket.
    expect(grouped).toEqual([["Identity", ["trading", "legal"]]]);
  });
});

describe("completion counts", () => {
  it("fieldsFilledCount only counts non-blank values", () => {
    expect(fieldsFilledCount({ a: "x", b: "  ", c: "" }, ["a", "b", "c", "d"])).toBe(1);
  });
  it("connectionIdsFor appends custom connections for that section", () => {
    const def = { fields: [], connections: ["ga4"] };
    const ids = connectionIdsFor("mk", def, { mk: [{ id: "xabc1", name: "Custom" }] });
    expect(ids).toEqual(["ga4", "xabc1"]);
  });
  it("connectionsConnectedCount only counts status === Connected", () => {
    const conns = { ga4: { status: "Connected" }, gsc: { status: "Not connected" } };
    expect(connectionsConnectedCount(conns, ["ga4", "gsc", "missing"])).toBe(1);
  });
});

describe("route model", () => {
  it("parses every segment shape", () => {
    expect(parseSectionRoute(undefined)).toEqual({ kind: "home" });
    expect(parseSectionRoute([])).toEqual({ kind: "home" });
    expect(parseSectionRoute(["company"])).toEqual({ kind: "company" });
    expect(parseSectionRoute(["mk"])).toEqual({ kind: "section", sectionId: "mk", sub: "overview" });
    expect(parseSectionRoute(["mk", "settings"])).toEqual({ kind: "section", sectionId: "mk", sub: "settings" });
    expect(parseSectionRoute(["mk", "3"])).toEqual({ kind: "section", sectionId: "mk", sub: "page", pageIndex: 3 });
  });
  it("falls back to home on a malformed route rather than throwing", () => {
    expect(parseSectionRoute(["mk", "not-a-number"])).toEqual({ kind: "home" });
    expect(parseSectionRoute(["mk", "settings", "extra"])).toEqual({ kind: "home" });
  });
  it("round-trips through sectionHref", () => {
    const base = "/clients/cl-1/profile";
    for (const segs of [undefined, ["company"], ["mk"], ["mk", "settings"], ["mk", "3"]]) {
      const route = parseSectionRoute(segs as string[] | undefined);
      expect(parseSectionRoute(sectionHref(base, route).slice(base.length + 1).split("/").filter(Boolean))).toEqual(route);
    }
  });
});

describe("patch builders — only changed keys, null/'' deletes", () => {
  it("buildProfilePatch emits only changed keys, deleting on blank", () => {
    const patch = buildProfilePatch({ a: "1", b: "2", c: "3" }, { a: "1", b: "2b", c: "" });
    expect(patch).toEqual({ b: "2b", c: null });
  });
  it("buildProfilePatch emits a brand-new key", () => {
    expect(buildProfilePatch({}, { legal: "Acme Ltd" })).toEqual({ legal: "Acme Ltd" });
  });
  it("buildConnectionsPatch diffs sub-keys and deletes the whole entry when removed", () => {
    const before = { ga4: { status: "Not connected", account: "" } };
    const after = { ga4: { status: "Connected", account: "GA-123" }, gsc: {} } as Record<string, { status?: string; account?: string }>;
    const patch = buildConnectionsPatch(before, after);
    expect(patch.ga4).toEqual({ status: "Connected", account: "GA-123" });
    expect(patch.gsc).toBeUndefined(); // an all-empty entry is not a change worth sending
    const removed = buildConnectionsPatch({ ga4: { status: "Connected" } }, {});
    expect(removed).toEqual({ ga4: null });
  });
  it("buildDepartmentsPatch: null means 'back to default' (key removed), not false", () => {
    expect(buildDepartmentsPatch({ mk: false }, {})).toEqual({ mk: null });
    expect(buildDepartmentsPatch({}, { mk: true })).toEqual({ mk: true });
    expect(buildDepartmentsPatch({ mk: true }, { mk: true })).toEqual({});
  });
  it("buildCustomConnectionsPatch replaces the whole list only when it changed", () => {
    const before = { mk: [{ id: "x1", name: "A" }] };
    const afterSame = { mk: [{ id: "x1", name: "A" }] };
    const afterChanged = { mk: [{ id: "x1", name: "A" }, { id: "x2", name: "B" }] };
    expect(buildCustomConnectionsPatch(before, afterSame)).toEqual({});
    expect(buildCustomConnectionsPatch(before, afterChanged)).toEqual({ mk: afterChanged.mk });
  });
  it("buildCentrePatch composes all four and returns null when nothing changed", () => {
    const draft: CentreDraft = {
      businessType: "hotel", profile: { legal: "Acme" }, connections: {}, departments: {}, customConnections: {},
    };
    expect(buildCentrePatch(draft, { ...draft })).toBeNull();
    const changed = buildCentrePatch(draft, { ...draft, businessType: "restaurant", profile: { legal: "" } });
    expect(changed).toEqual({ businessType: "restaurant", profile: { legal: null } });
  });
  it("applyPatchToDraft is the inverse merge buildCentrePatch expects", () => {
    const draft: CentreDraft = {
      businessType: "hotel", profile: { legal: "Acme" }, connections: { ga4: { status: "Not connected" } },
      departments: {}, customConnections: {},
    };
    const patch = buildCentrePatch(draft, {
      ...draft, profile: { legal: "Acme Ltd" }, connections: { ga4: { status: "Connected" } }, departments: { mk: false },
    })!;
    const applied = applyPatchToDraft(draft, patch);
    expect(applied.profile.legal).toBe("Acme Ltd");
    expect(applied.connections.ga4.status).toBe("Connected");
    expect(applied.departments.mk).toBe(false);
    // Round trip: diffing draft -> applied now yields nothing further to send.
    expect(buildCentrePatch(draft, applied)).toEqual(patch);
  });
});

describe("draftFromProfile", () => {
  it("produces an independent, deep-enough copy (mutating it never touches the source profile)", () => {
    const profile: CentreProfile = {
      clientId: "cl-1", clientName: "Demo Harbour Hotel", clientStatus: "active", businessType: "hotel",
      profile: { legal: "Demo Harbour Hotel Ltd" },
      connections: { ga4: { status: "Connected" } },
      departments: {},
      customConnections: { mk: [{ id: "x1", name: "Custom" }] },
      revision: 1, updatedAt: null, updatedBy: null, canEdit: true,
    };
    const draft = draftFromProfile(profile);
    draft.profile.legal = "Changed";
    draft.connections.ga4.status = "Not connected";
    draft.customConnections.mk[0].name = "Changed";
    expect(profile.profile.legal).toBe("Demo Harbour Hotel Ltd");
    expect(profile.connections.ga4.status).toBe("Connected");
    expect(profile.customConnections.mk[0].name).toBe("Custom");
  });
});

describe("businessTypeLabel", () => {
  it("looks up the label, falling back to Other", () => {
    expect(businessTypeLabel(registry, "hotel")).toBe("Hotel / villa / accommodation");
    expect(businessTypeLabel(registry, "not-a-real-type")).toBe("Other");
  });
});

// Type-only smoke check that the imported registry satisfies its declared shape.
const _typeCheck: ClientCentreRegistry = registry;
void _typeCheck;
