// GENERATED by scripts/generate-office-credits.mjs — do not hand-edit.
// Run `npm run gen:office-credits` from platform-ui/ to regenerate against a fresh CREDITS.csv.
// Source project: https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator
// Generated at: 2026-08-23T06:10:18.822Z

export interface OfficeCreditEntry {
  file: string;
  authors: string[];
  licence: string;
  url: string;
}

/** The 24 shipped LPC sprite files, one entry per file, licence ELECTED per
 *  legal/asset-licences.md (OGA-BY 3.0 preferred, CC0 otherwise — never CC-BY-SA). */
export const OFFICE_CREDITS: OfficeCreditEntry[] = [
  {
    "file": "body/bodies/female/sit.png",
    "authors": [
      "Benjamin K. Smith (BenCreating)",
      "bluecarrot16",
      "TheraHedwig",
      "Evert",
      "MuffinElZangano",
      "Durrani",
      "Pierre Vigier (pvigier)",
      "ElizaWy",
      "Matthew Krohn (makrohn)",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/body/bodies/female/sit.png"
  },
  {
    "file": "body/bodies/female/walk.png",
    "authors": [
      "Benjamin K. Smith (BenCreating)",
      "bluecarrot16",
      "TheraHedwig",
      "Evert",
      "MuffinElZangano",
      "Durrani",
      "Pierre Vigier (pvigier)",
      "ElizaWy",
      "Matthew Krohn (makrohn)",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/body/bodies/female/walk.png"
  },
  {
    "file": "body/bodies/male/sit.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "Benjamin K. Smith (BenCreating)",
      "Evert",
      "Eliza Wyatt (ElizaWy)",
      "TheraHedwig",
      "MuffinElZangano",
      "Durrani",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/body/bodies/male/sit.png"
  },
  {
    "file": "body/bodies/male/walk.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "Benjamin K. Smith (BenCreating)",
      "Evert",
      "Eliza Wyatt (ElizaWy)",
      "TheraHedwig",
      "MuffinElZangano",
      "Durrani",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/body/bodies/male/walk.png"
  },
  {
    "file": "feet/shoes/basic/male/sit.png",
    "authors": [
      "JaidynReiman",
      "bluecarrot16",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/feet/shoes/basic/male/sit.png"
  },
  {
    "file": "feet/shoes/basic/male/walk.png",
    "authors": [
      "JaidynReiman",
      "bluecarrot16",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/feet/shoes/basic/male/walk.png"
  },
  {
    "file": "feet/shoes/basic/thin/sit.png",
    "authors": [
      "JaidynReiman",
      "Joe White",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/feet/shoes/basic/thin/sit.png"
  },
  {
    "file": "feet/shoes/basic/thin/walk.png",
    "authors": [
      "JaidynReiman",
      "Joe White",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/feet/shoes/basic/thin/walk.png"
  },
  {
    "file": "hair/bob/adult/sit.png",
    "authors": [
      "ElizaWy",
      "bluecarrot16"
    ],
    "licence": "CC0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/hair/bob/adult/sit.png"
  },
  {
    "file": "hair/bob/adult/walk.png",
    "authors": [
      "ElizaWy",
      "bluecarrot16"
    ],
    "licence": "CC0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/hair/bob/adult/walk.png"
  },
  {
    "file": "hair/buzzcut/adult/sit.png",
    "authors": [
      "ElizaWy"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/hair/buzzcut/adult/sit.png"
  },
  {
    "file": "hair/buzzcut/adult/walk.png",
    "authors": [
      "ElizaWy"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/hair/buzzcut/adult/walk.png"
  },
  {
    "file": "head/heads/human/female/sit.png",
    "authors": [
      "bluecarrot16",
      "Benjamin K. Smith (BenCreating)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/head/heads/human/female/sit.png"
  },
  {
    "file": "head/heads/human/female/walk.png",
    "authors": [
      "bluecarrot16",
      "Benjamin K. Smith (BenCreating)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/head/heads/human/female/walk.png"
  },
  {
    "file": "head/heads/human/male/sit.png",
    "authors": [
      "bluecarrot16",
      "Benjamin K. Smith (BenCreating)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/head/heads/human/male/sit.png"
  },
  {
    "file": "head/heads/human/male/walk.png",
    "authors": [
      "bluecarrot16",
      "Benjamin K. Smith (BenCreating)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/head/heads/human/male/walk.png"
  },
  {
    "file": "legs/formal/male/sit.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "ElizaWy",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/legs/formal/male/sit.png"
  },
  {
    "file": "legs/formal/male/walk.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "ElizaWy",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/legs/formal/male/walk.png"
  },
  {
    "file": "legs/formal/thin/sit.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "ElizaWy",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/legs/formal/thin/sit.png"
  },
  {
    "file": "legs/formal/thin/walk.png",
    "authors": [
      "bluecarrot16",
      "JaidynReiman",
      "ElizaWy",
      "Johannes Sjölund (wulax)",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/legs/formal/thin/walk.png"
  },
  {
    "file": "torso/clothes/longsleeve/longsleeve/female/sit.png",
    "authors": [
      "bluecarrot16",
      "ElizaWy",
      "JaidynReiman",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/torso/clothes/longsleeve/longsleeve/female/sit.png"
  },
  {
    "file": "torso/clothes/longsleeve/longsleeve/female/walk.png",
    "authors": [
      "bluecarrot16",
      "ElizaWy",
      "JaidynReiman",
      "Stephen Challener (Redshrike)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/torso/clothes/longsleeve/longsleeve/female/walk.png"
  },
  {
    "file": "torso/clothes/longsleeve/longsleeve/male/sit.png",
    "authors": [
      "JaidynReiman",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/torso/clothes/longsleeve/longsleeve/male/sit.png"
  },
  {
    "file": "torso/clothes/longsleeve/longsleeve/male/walk.png",
    "authors": [
      "JaidynReiman",
      "Johannes Sjölund (wulax)"
    ],
    "licence": "OGA-BY 3.0",
    "url": "https://github.com/liberatedpixelcup/Universal-LPC-Spritesheet-Character-Generator/blob/master/spritesheets/torso/clothes/longsleeve/longsleeve/male/walk.png"
  }
];

/** Every distinct contributing artist across the shipped set, sorted. */
export const OFFICE_CREDIT_AUTHORS: string[] = [
  "Benjamin K. Smith (BenCreating)",
  "bluecarrot16",
  "Durrani",
  "Eliza Wyatt (ElizaWy)",
  "ElizaWy",
  "Evert",
  "JaidynReiman",
  "Joe White",
  "Johannes Sjölund (wulax)",
  "Matthew Krohn (makrohn)",
  "MuffinElZangano",
  "Pierre Vigier (pvigier)",
  "Stephen Challener (Redshrike)",
  "TheraHedwig"
];
