// Sample rows for the Repositories tab's PREVIEW mode (`?preview=sample`). Client-safe, pure data.
//
// Why this exists: on a platform where nothing has been provisioned yet the tab is (correctly) empty,
// which makes the layout impossible to review. Preview renders these rows behind a banner that says
// they are samples. They are shaped exactly like real rows (`RepoRow`), cover every status the
// backend can produce, and use the same client/project/run vocabulary as the rest of the app.
// Never shown without the banner; never mixed with real rows.
import type { RepoRow } from "./repoInventory";

export const SAMPLE_REPO_ROWS: RepoRow[] = [
  {
    id: "sample-failed",
    name: "northwind-checkout-revamp",
    status: "failed",
    framework: "nextjs",
    frameworkLabel: "Next.js",
    repoUrl: null,
    stagingUrl: null,
    clientName: "Northwind Traders",
    projectName: "Checkout revamp",
    run: { id: "sample-run-3", title: "Northwind — checkout flow scope call" },
    requestedAt: "2026-08-25T04:10:00Z",
    lastCheckedAt: null,
    failure: {
      title: "That name belongs to someone else's site",
      body: "A site with this name already exists on the provisioning host and isn't ours. Pick a different slug and provision again.",
      remedy: "reprovision",
    },
    canReconcile: false,
  },
  {
    id: "sample-pending",
    name: "cedar-group-brand-site",
    status: "pending",
    framework: "vite",
    frameworkLabel: "Vite (static)",
    repoUrl: null,
    stagingUrl: null,
    clientName: "Cedar Group",
    projectName: "Brand site",
    run: { id: "sample-run-4", title: "Cedar Group — brand site kickoff" },
    requestedAt: "2026-08-26T02:40:00Z",
    lastCheckedAt: "2026-08-26T02:41:00Z",
    failure: null,
    canReconcile: true,
  },
  {
    id: "sample-provisioned",
    name: "lumen-studio-portfolio",
    status: "provisioned",
    framework: "nextjs",
    frameworkLabel: "Next.js",
    repoUrl: "https://github.com/Gaia-Digital-Agency/lumen-studio-portfolio",
    stagingUrl: "https://lumen-studio-portfolio.gaiada.online",
    clientName: "Lumen Studio",
    projectName: "Portfolio site",
    run: { id: "sample-run-2", title: "Lumen — portfolio discovery" },
    requestedAt: "2026-08-20T08:00:00Z",
    lastCheckedAt: "2026-08-26T01:00:00Z",
    failure: null,
    canReconcile: true,
  },
  {
    id: "sample-live-1",
    name: "northwind-site-redesign",
    status: "live",
    framework: "nextjs",
    frameworkLabel: "Next.js",
    repoUrl: "https://github.com/Gaia-Digital-Agency/northwind-site-redesign",
    stagingUrl: "https://northwind-site-redesign.gaiada.online",
    clientName: "Northwind Traders",
    projectName: "Client site redesign",
    run: { id: "sample-run-1", title: "Northwind — site redesign kickoff" },
    requestedAt: "2026-07-18T03:30:00Z",
    lastCheckedAt: "2026-08-26T01:00:00Z",
    failure: null,
    canReconcile: false,
  },
  {
    id: "sample-live-2",
    name: "sanur-resort-booking",
    status: "live",
    framework: "vite",
    frameworkLabel: "Vite (static)",
    repoUrl: "https://github.com/Gaia-Digital-Agency/sanur-resort-booking",
    stagingUrl: "https://sanur-resort-booking.gaiada.online",
    clientName: "Sanur Resort",
    projectName: "Booking microsite",
    run: { id: "sample-run-0", title: "Sanur — booking microsite brief" },
    requestedAt: "2026-06-30T06:00:00Z",
    lastCheckedAt: "2026-08-25T01:00:00Z",
    failure: null,
    canReconcile: false,
  },
];
