// WSK-20 — the `astro` siteKind skeleton: fully static output. See page-composer.ts's header for
// why `astro`/`node` share every page-composition file and differ only here.
import type { GeneratedFile } from "../page-composer";

export function astroConfig(): GeneratedFile {
  return {
    path: "astro.config.mjs",
    content:
      `// GENERATED by code.scaffold v2 (WSK-20). siteKind: astro — static output.\n` +
      `import { defineConfig } from "astro/config";\n\n` +
      `export default defineConfig({\n` +
      `  output: "static",\n` +
      `});\n`,
  };
}
