// WSK-20 — file fragments shared by both site-kind templates. Every value here is a STRING the
// scaffolder composes; none of it is ever executed by this process (WSK-D6).
import type { GeneratedFile } from "../page-composer";

export function gitignore(): GeneratedFile {
  return {
    path: ".gitignore",
    content: `node_modules/\ndist/\n.astro/\n.env\n*.log\n`,
  };
}

export function envExample(): GeneratedFile {
  return {
    path: ".env.example",
    content:
      `# GENERATED by code.scaffold v2 (WSK-20). Filled in by the environment (repo CI secrets /\n` +
      `# Zone B preview injection) — never committed with real values.\n` +
      `WEBDESK_HOST=\n` +
      `WEBDESK_API_KEY=\n`,
  };
}

export function readme(args: { siteKind: string; tenantSlug: string; blockLibraryVersion: string }): GeneratedFile {
  return {
    path: "README.md",
    content:
      `# Generated WebDesk site (${args.siteKind})\n\n` +
      `Scaffolded by \`code.scaffold\` v2 (WSK-20) from a signed PRD + an accepted prototype, pinned to a\n` +
      `contract snapshot for tenant \`${args.tenantSlug}\`. See \`CONTRACT.lock\` at repo root for the exact\n` +
      `pin. Block-renderer library: \`@gaiada/webdesk-blocks@${args.blockLibraryVersion}\`.\n\n` +
      `## What this repo does NOT do\n\n` +
      `This repo was composed and pushed by the agent-runner; it was never \`npm install\`-ed or run in\n` +
      `that process (webdesk-design.md §06, decision WSK-D6). The first \`npm install\`/build/test happens\n` +
      `in repo CI or a Zone B preview — never in the scaffolder.\n\n` +
      `## Vocabulary gaps\n\n` +
      `Any page the prototype referenced that the pinned contract snapshot could not satisfy was left as\n` +
      `a TODO stub, with a draft schema proposal under \`webdesk-schema-proposals/\`. Nothing there is\n` +
      `applied automatically — a human submits it via the console's schema-propose flow (WSK-32).\n`,
  };
}

export function tsconfig(): GeneratedFile {
  return {
    path: "tsconfig.json",
    content:
      JSON.stringify(
        {
          extends: "astro/tsconfigs/strict",
          compilerOptions: { types: ["astro/client"] },
        },
        null,
        2,
      ) + "\n",
  };
}

/** The block library + generated SDK are both installed as FILES (OQ-6: "no registry infra") — a
 *  `file:` dependency pointing at the tarballs the git-writer vendors into the repo, never a registry
 *  publish/fetch. `npm install` itself never runs here (WSK-D6) — this is what repo CI's OWN install
 *  step resolves. */
export function packageJson(args: {
  name: string;
  siteKind: "astro" | "node";
  blockLibraryVersion: string;
  astroVersion?: string;
}): GeneratedFile {
  const astroVersion = args.astroVersion ?? "^7.2.8";
  const base = {
    name: args.name,
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: {
      dev: "astro dev",
      build: "astro build",
      preview: "astro preview",
      test: "vitest run",
    },
    dependencies: {
      astro: astroVersion,
      "@gaiada/webdesk-blocks": "file:./vendor/webdesk-blocks.tgz",
      "@gaiada/webdesk-sdk": "file:./vendor/webdesk-sdk.tgz",
    },
    devDependencies: {
      vitest: "^2.1.5",
      typescript: "^5.6.3",
    },
  } as Record<string, unknown>;
  if (args.siteKind === "node") {
    (base.dependencies as Record<string, string>)["@astrojs/node"] = "^9.0.0";
  }
  return { path: "package.json", content: JSON.stringify(base, null, 2) + "\n" };
}
