// WSK-20 — the `node` siteKind skeleton: SSR output via @astrojs/node. See page-composer.ts's
// header for why `astro`/`node` share every page-composition file and differ only here.
import type { GeneratedFile } from "../page-composer";

export function astroConfig(): GeneratedFile {
  return {
    path: "astro.config.mjs",
    content:
      `// GENERATED by code.scaffold v2 (WSK-20). siteKind: node — SSR via @astrojs/node.\n` +
      `import { defineConfig } from "astro/config";\n` +
      `import node from "@astrojs/node";\n\n` +
      `export default defineConfig({\n` +
      `  output: "server",\n` +
      `  adapter: node({ mode: "standalone" }),\n` +
      `});\n`,
  };
}
