// WSK-20 / WSK-D28 (webdesk-design-v2.md §08) — the `siteKind: "wp"` template, wired.
//
// Ported, near-verbatim, from `webdesk/wordpress/scaffold-template/wp-site.ts` (WSK-35) — that
// file's own header says exactly this is what it is for: "the template WSK-20 would call INSTEAD
// of refusing, once a follow-up ticket replaces that branch with a dispatch to it." §08 is that
// follow-up ticket's ruling ("lift rejected_site_kind, wire the PHP SDK path... the WP theme
// scaffold ALREADY EXISTS — do not create one"). This is a PORT, not a new template: every
// generated file's content is unchanged from the source; only the argument shape is adapted to
// this project's own `GeneratedFile`/template-argument idiom (`templates/astro-site.ts`,
// `templates/node-site.ts`) so `scaffold.ts` can call it exactly like the other two site kinds.
//
// `ai-agents` and `webdesk` are separate standalone projects (repo root CLAUDE.md: "no monorepo,
// no shared package layer") — this file cannot literally `import` the source, exactly as that
// source file's own header explains for the reverse direction. Keeping both copies is a deliberate
// duplication-with-provenance-comment, the same idiom `webdesk/wordpress/inc/block-vocabulary.php`
// already uses for the block vocabulary (vendor-with-a-drift-check, not a workaround).
import type { GeneratedFile } from "../page-composer";

export interface WpSiteTemplateArgs {
  tenantSlug: string;
  /** The PHP SDK's own generated bytes for this tenant (WSK-34's `sdk-php.mts` output), read from
   *  the pinned contract snapshot's `artifacts.sdkPhp` file — see `contract-snapshot-provider.ts`.
   *  Composed into `vendor/gaiada-sdk/sdk.php` verbatim, never re-derived or hand-edited here. */
  sdkPhpSource: string;
  contractVersion: string;
  vocabularyVersion: string;
}

/** WordPress theme's required `style.css` header comment — the ONLY file WordPress itself parses
 *  to discover a theme (no build step, no package.json — the theme IS the deployable unit on
 *  shared hosting with no shell-access model, per `infra/runbooks/onboard-server.md`). */
export function themeStyleCss(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "style.css",
    content:
      `/*\n` +
      `Theme Name: Gaiada WebDesk — ${args.tenantSlug}\n` +
      `Description: GENERATED by code.scaffold v2's siteKind:"wp" template (WSK-35/WSK-D28). Headless-\n` +
      `  consumer theme: every page renders content fetched through the generated PHP SDK\n` +
      `  (vendor/gaiada-sdk/sdk.php, WSK-34), never WordPress's own post/page content. Pinned to\n` +
      `  contract v${args.contractVersion} / vocabulary v${args.vocabularyVersion}.\n` +
      `Author: Gaiada\n` +
      `Version: ${args.contractVersion}\n` +
      `Requires PHP: 8.1\n` +
      `*/\n`,
  };
}

/** The vendored PHP SDK — dropped in as a plain file, never installed via Composer (no shell/
 *  Composer-install model on shared hosting, mirroring how the TS SDK is vendored as a `.tgz` for
 *  the astro/node kinds — see `git-writer.ts`'s `vendorFiles`). */
export function vendoredSdkPhp(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "vendor/gaiada-sdk/sdk.php",
    content: args.sdkPhpSource,
  };
}

/** Theme bootstrap: reads the tenant's base URL + API key from WordPress options or `wp-config.php`
 *  constants (never hardcoded, never committed with a real key — mirrors `templates/common.ts`'s
 *  `envExample()` pattern) and exposes one `gaiada_webdesk_client()` helper the rest of the theme
 *  calls. */
export function functionsPhp(): GeneratedFile {
  return {
    path: "functions.php",
    content:
      `<?php\n` +
      `// GENERATED by code.scaffold v2 (WSK-35/WSK-D28). siteKind: wp — headless WordPress theme.\n` +
      `declare(strict_types=1);\n\n` +
      `require_once __DIR__ . '/vendor/gaiada-sdk/sdk.php';\n` +
      `require_once __DIR__ . '/inc/block-vocabulary.php';\n` +
      `require_once __DIR__ . '/inc/block-renderer.php';\n\n` +
      `use GaiadaWebDesk\\Sdk\\WebDeskClient;\n\n` +
      `/**\n` +
      ` * The one client instance the theme's templates call. Base URL + API key come from\n` +
      ` * WordPress options or wp-config.php constants (GAIADA_WEBDESK_BASE_URL /\n` +
      ` * GAIADA_WEBDESK_API_KEY) — never a value baked into this generated file.\n` +
      ` */\n` +
      `function gaiada_webdesk_client(): WebDeskClient {\n` +
      `    static $client = null;\n` +
      `    if ($client === null) {\n` +
      `        $baseUrl = defined('GAIADA_WEBDESK_BASE_URL') ? GAIADA_WEBDESK_BASE_URL : (get_option('gaiada_webdesk_base_url') ?: '');\n` +
      `        $apiKey = defined('GAIADA_WEBDESK_API_KEY') ? GAIADA_WEBDESK_API_KEY : (get_option('gaiada_webdesk_api_key') ?: '');\n` +
      `        $client = new WebDeskClient($baseUrl, $apiKey);\n` +
      `    }\n` +
      `    return $client;\n` +
      `}\n`,
  };
}

/** A minimal `page.php` — the theme's ONLY page template, since every page is a WebDesk item, not
 *  WP content. Renders the render-time half of the renderer invariant (webdesk-design.md §05 hard
 *  rule 2): an unknown block type is SKIPPED AND REPORTED, never rejected, never silently dropped. */
export function pagePhp(): GeneratedFile {
  return {
    path: "page.php",
    content:
      `<?php\n` +
      `// GENERATED by code.scaffold v2 (WSK-35/WSK-D28). Renders ONE WebDesk item via the block\n` +
      `// renderer — see inc/block-renderer.php's gaiada_render_blocks().\n` +
      `declare(strict_types=1);\n\n` +
      `get_header();\n\n` +
      `$collection = get_query_var('gaiada_collection', 'article');\n` +
      `$slug = get_query_var('gaiada_slug', '');\n` +
      `$method = 'get' . implode('', array_map('ucfirst', preg_split('/[^A-Za-z0-9]+/', $collection)));\n\n` +
      `try {\n` +
      `    $item = call_user_func([gaiada_webdesk_client(), $method], $slug);\n` +
      `} catch (\\Throwable $e) {\n` +
      `    echo '<p>Content unavailable.</p>';\n` +
      `    get_footer();\n` +
      `    return;\n` +
      `}\n\n` +
      `if (!empty($item['meta']['draft'])) {\n` +
      `    echo '<div class="gaiada-draft-banner">Draft preview</div>';\n` +
      `}\n\n` +
      `echo gaiada_render_blocks($item['blocks'] ?? [], $collection, $slug);\n\n` +
      `get_footer();\n`,
  };
}

export function themeReadme(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "README.md",
    content:
      `# Generated WebDesk theme (wp) — ${args.tenantSlug}\n\n` +
      `Scaffolded by \`code.scaffold\` v2's \`siteKind:"wp"\` template (WSK-35/WSK-D28), consuming the\n` +
      `PHP SDK generated by WSK-34 for contract v${args.contractVersion}.\n\n` +
      `## What this repo does NOT do\n\n` +
      `Composed and pushed by the agent-runner, never \`npm install\`/\`composer install\`/executed in\n` +
      `that process (WSK-D6). Deploying this theme to a real WordPress install (activating it in\n` +
      `wp-admin, wiring the \`gaiada_collection\`/\`gaiada_slug\` rewrite rules) is a real theme-\n` +
      `authoring/ops task this scaffold does not perform.\n`,
  };
}

/** Composes every file the `wp` kind contributes. Called by `scaffold.ts` in place of the old
 *  `rejectedResult(...)` branch (WSK-D28 / §08). */
export function wpSiteFiles(args: WpSiteTemplateArgs): GeneratedFile[] {
  return [themeStyleCss(args), vendoredSdkPhp(args), functionsPhp(), pagePhp(), themeReadme(args)];
}
