// webdesk/wordpress/scaffold-template/wp-site.ts
//
// WSK-35 — the `siteKind: "wp"` template pattern that `code.scaffold` v2 (WSK-20,
// ai-agents/src/code-scaffold/) will compose once someone wires it in. Today
// `ai-agents/src/code-scaffold/scaffold.ts` (lines ~33-36) EXPLICITLY REFUSES `siteKind: "wp"`
// with the message "wp is P6/WSK-35 — do not build" — that refusal is correct scoping by WSK-20
// and is UNTOUCHED here, per this ticket's brief ("ai-agents/, already DEV-VERIFIED — read what
// it does, do not modify it"). This file is the thing that refusal was deferring: the template
// WSK-20's scaffolder would call INSTEAD of refusing, once a follow-up ticket replaces that
// `rejectedResult(...)` branch with a dispatch to the functions below — see this directory's
// README for the exact integration point and why it is out of THIS ticket's owned files.
//
// Shape mirrors `ai-agents/src/code-scaffold/templates/{astro-site,node-site,common}.ts` exactly
// (same `GeneratedFile { path, content }` contract, same "every value here is a STRING the
// scaffolder composes; none of it is ever executed by this process" invariant, WSK-D6) — but
// cannot literally `import` that module: `ai-agents` and `webdesk` are separate standalone
// projects per the repo root CLAUDE.md ("no monorepo, no shared package layer"). `GeneratedFile`
// is therefore restated here as a structurally identical local type, not re-exported.
export interface GeneratedFile {
  path: string;
  content: string;
}

export interface WpSiteTemplateArgs {
  tenantSlug: string;
  /** The PHP SDK's own bytes for this tenant — i.e. `built.sdkPhp` from
   *  `webdesk/api/src/codegen/generator/build-artifacts.mts` (WSK-34), or (in a real scaffold run)
   *  the artifact fetched from `GET /control/v1/tenants/:slug/contract`'s `artifacts.sdkPhpUrl`.
   *  Composed into `vendor/gaiada-sdk/sdk.php` verbatim, never re-derived or hand-edited here —
   *  exactly the same "regeneration is authoritative" rule the TS SDK's `file:./vendor/*.tgz`
   *  pattern already establishes in `templates/common.ts`'s `packageJson()`. */
  sdkPhpSource: string;
  contractVersion: string;
  vocabularyVersion: string;
}

/** WordPress theme's required `style.css` header comment — the ONLY file WordPress itself parses
 *  to discover a theme (no build step, no package.json — the theme IS the deployable unit on
 *  Hostinger shared hosting, per `infra/runbooks/onboard-server.md`: no shell-access model, so
 *  this must be a plain file drop, never an `npm install`/`composer install` step). */
export function themeStyleCss(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "style.css",
    content:
      `/*\n` +
      `Theme Name: Gaiada WebDesk — ${args.tenantSlug}\n` +
      `Description: GENERATED by code.scaffold v2's siteKind:"wp" template (WSK-35). Headless-\n` +
      `  consumer theme: every page renders content fetched through the generated PHP SDK\n` +
      `  (vendor/gaiada-sdk/sdk.php, WSK-34), never WordPress's own post/page content. Pinned to\n` +
      `  contract v${args.contractVersion} / vocabulary v${args.vocabularyVersion}.\n` +
      `Author: Gaiada\n` +
      `Version: ${args.contractVersion}\n` +
      `Requires PHP: 8.1\n` +
      `*/\n`,
  };
}

/** The vendored PHP SDK — dropped in as a plain file, never installed via Composer. Hostinger
 *  shared hosting has no shell/Composer-install model available to a scaffolder that only ever
 *  composes files and pushes (WSK-D6) — so "vendoring" here means literally what WSK-16's
 *  `webdesk/blocks` vendoring means for the vocabulary: a verbatim copy with a clear provenance
 *  comment, never a hand-maintained second copy. */
export function vendoredSdkPhp(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "vendor/gaiada-sdk/sdk.php",
    content: args.sdkPhpSource,
  };
}

/** Theme bootstrap: reads the tenant's base URL + API key from WordPress options (set via the
 *  admin UI or `wp-config.php` constants — never hardcoded, never committed with a real key,
 *  mirroring `templates/common.ts`'s `envExample()` pattern for the Astro/Node kinds) and exposes
 *  one `gaiada_webdesk_client()` helper the rest of the theme calls. */
export function functionsPhp(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "functions.php",
    content:
      `<?php\n` +
      `// GENERATED by code.scaffold v2 (WSK-35). siteKind: wp — headless WordPress theme.\n` +
      `declare(strict_types=1);\n\n` +
      `require_once __DIR__ . '/vendor/gaiada-sdk/sdk.php';\n` +
      `require_once __DIR__ . '/inc/block-vocabulary.php';\n` +
      `require_once __DIR__ . '/inc/block-renderer.php';\n\n` +
      `use GaiadaWebDesk\\Sdk\\WebDeskClient;\n\n` +
      `/**\n` +
      ` * The one client instance the theme's templates call. Base URL + API key come from\n` +
      ` * WordPress options (Settings -> General -> a small settings panel this theme could add;\n` +
      ` * out of this ticket's scope to build a full admin UI) or, failing that, wp-config.php\n` +
      ` * constants (GAIADA_WEBDESK_BASE_URL / GAIADA_WEBDESK_API_KEY) — never a value baked into\n` +
      ` * this generated file, matching the Astro/Node kinds' own ".env.example, never committed\n` +
      ` * with real values" rule.\n` +
      ` */\n` +
      `function gaiada_webdesk_client(): WebDeskClient {\n` +
      `    static $client = null;\n` +
      `    if ($client === null) {\n` +
      `        $baseUrl = defined('GAIADA_WEBDESK_BASE_URL') ? GAIADA_WEBDESK_BASE_URL : (get_option('gaiada_webdesk_base_url') ?: '');\n` +
      `        $apiKey = defined('GAIADA_WEBDESK_API_KEY') ? GAIADA_WEBDESK_API_KEY : (get_option('gaiada_webdesk_api_key') ?: '');\n` +
      `        $client = new WebDeskClient($baseUrl, $apiKey);\n` +
      `    }\n` +
      `    return $client;\n` +
      `}\n`,
  };
}

/** A minimal `page.php` — the theme's ONLY page template, since every page is a WebDesk item, not
 *  WP content. Resolves the item's collection/slug from the query var this theme's (not built
 *  here — WordPress rewrite-rule wiring is a real theme-authoring task, honestly out of a
 *  generated-file's reach) would set, then hands the item's `blocks` array to the renderer. */
export function pagePhp(): GeneratedFile {
  return {
    path: "page.php",
    content:
      `<?php\n` +
      `// GENERATED by code.scaffold v2 (WSK-35). Renders ONE WebDesk item via the block renderer —\n` +
      `// the render-time half of the renderer invariant (webdesk-design.md §05 hard rule 2): an\n` +
      `// unknown block type is SKIPPED AND REPORTED here, never rejected (composition-time rejection\n` +
      `// is WSK-14's job, on a different collection entirely) and never silently dropped without a\n` +
      `// trace — see inc/block-renderer.php's gaiada_render_blocks().\n` +
      `declare(strict_types=1);\n\n` +
      `get_header();\n\n` +
      `$collection = get_query_var('gaiada_collection', 'article');\n` +
      `$slug = get_query_var('gaiada_slug', '');\n` +
      `$method = 'get' . implode('', array_map('ucfirst', preg_split('/[^A-Za-z0-9]+/', $collection)));\n\n` +
      `try {\n` +
      `    $item = call_user_func([gaiada_webdesk_client(), $method], $slug);\n` +
      `} catch (\\Throwable $e) {\n` +
      `    echo '<p>Content unavailable.</p>';\n` +
      `    get_footer();\n` +
      `    return;\n` +
      `}\n\n` +
      `if (!empty($item['meta']['draft'])) {\n` +
      `    echo '<div class="gaiada-draft-banner">Draft preview</div>';\n` +
      `}\n\n` +
      `echo gaiada_render_blocks($item['blocks'] ?? [], $collection, $slug);\n\n` +
      `get_footer();\n`,
  };
}

export function themeReadme(args: WpSiteTemplateArgs): GeneratedFile {
  return {
    path: "README.md",
    content:
      `# Generated WebDesk theme (wp) — ${args.tenantSlug}\n\n` +
      `Scaffolded by \`code.scaffold\` v2's \`siteKind:"wp"\` template (WSK-35), consuming the\n` +
      `PHP SDK generated by WSK-34 for contract v${args.contractVersion}.\n\n` +
      `## Deployment reality (read before assuming a server-side install)\n\n` +
      `Tenant zero (\`gaiada.com\`) is on Hostinger **shared hosting**, which per\n` +
      `\`infra/runbooks/onboard-server.md\` has **no shell-access model**. This theme is therefore a\n` +
      `**plain file drop, never a Composer/npm install target**: the PHP SDK is vendored verbatim\n` +
      `into \`vendor/gaiada-sdk/sdk.php\` at scaffold time (or at CI/regeneration time — never\n` +
      `hand-edited; see that file's own \`DO NOT HAND-EDIT\` banner). Deploying this theme to the\n` +
      `real gaiada.com is a **DNS + content-export exercise** (upload the theme via the host's file\n` +
      `manager or SFTP if the plan offers it, activate it in wp-admin) — this ticket did NOT perform\n` +
      `that deployment; the real site was never touched.\n\n` +
      `## What this repo does NOT do\n\n` +
      `Matches \`templates/common.ts\`'s \`readme()\` for the astro/node kinds: composed and pushed by\n` +
      `the agent-runner, never \`npm install\`/\`composer install\`/executed in that process (WSK-D6).\n`,
  };
}

/** Composes every file this template contributes — the function a wired-up `scaffold.ts` would
 *  call in place of today's `rejectedResult(...)` branch for `siteKind === "wp"`. */
export function wpSiteFiles(args: WpSiteTemplateArgs): GeneratedFile[] {
  return [themeStyleCss(args), vendoredSdkPhp(args), functionsPhp(args), pagePhp(), themeReadme(args)];
}
