// IAM-SEC-06 — the role -> reachable-scope-type source `assemblePrincipal()` filters resolved
// permissions through. See docs/superpowers/plans/2026-08-13-iam-sec-06-report.md and the ruling it
// implements, docs/superpowers/plans/2026-08-12-iam-04c-ruling.md §8 option (A).
//
// THE DEFECT THIS CLOSES: `assemblePrincipal()` copies a grant's `scope_type`/`scope_id` verbatim
// onto every permission it resolves through that grant. A grant recorded at a scope the role's OWN
// Cerbos derived-role condition (`cerbos/policies/derived_roles.yaml`) can never be satisfied at
// (`platform_admin@company`, `org_unit_lead@company`, `client@global`, …) is INERT under role-name
// matching (Cerbos never grants it — the role arm's own condition refuses that scope) but is NOT
// inert under permission matching: a `perm_*` mirror that only checks "global-or-company" would
// honour the resolved permission at that same mis-scoped scope, granting exactly what the role arm
// denies. `IAM-SEC-05` closed the two WRITE paths that could mint such a grant
// (`admin-identity.controller.ts`'s `ROLE_SCOPE_CONSTRAINTS`); the architect ruled that a write-path
// guard is the wrong LAYER to rely on (seeds/migrations write grants directly by design, and a guard
// is only as good as its completeness — proven incomplete once already). This module is the fix at
// the layer that actually decides: strip the poisoned PERMISSION at resolution time, regardless of
// how the underlying grant row came to exist.
//
// MACHINE-DERIVED, NOT A SECOND HAND-MAINTAINED LIST: `scope-constrained-roles.json` is generated by
// `scripts/generate-scope-constrained-roles.mjs` directly from `derived_roles.yaml` — it is a
// SEPARATE artifact from `admin-identity.controller.ts`'s `ROLE_SCOPE_CONSTRAINTS` (which serves the
// write-path guard, a different layer), not a duplicate of it; both are independently checked against
// the SAME policy source so neither can drift from the ground truth even though they are not the same
// object. `scope-constrained-roles.test.ts` asserts this checked-in JSON is byte-identical to a fresh
// regeneration on every run — editing `derived_roles.yaml` without regenerating turns that test RED.
//
// FAIL-OPEN BY DESIGN for any role name absent from the map (most roles: company_admin/manager/
// member/viewer/module_staff-composed names/... all have EITHER no scope narrowing at all, or a
// narrowing this map already captures precisely). Only a role whose OWN Cerbos condition is provably
// narrower than "global-or-company" (as re-derived from the policy text, never guessed) gets an
// entry — see the generator script's header for exactly how that set is computed. Getting the
// direction backwards (failing CLOSED for an unlisted role) would drop every permission for every
// role that doesn't happen to appear as a literal `g.role == "..."` in derived_roles.yaml — most of
// the estate — which is why `scope-constrained-roles.test.ts` pins the unconstrained-role case as its
// own dedicated assertion, not just an implicit default.
import scopeConstrainedRolesDoc from "./scope-constrained-roles.json";

export type ScopeType = "global" | "company" | "org_unit" | "project";

interface ScopeConstrainedRolesDoc {
  roles: Record<string, string[]>;
}

const SCOPE_CONSTRAINED_ROLES: ReadonlyMap<string, ReadonlySet<string>> = new Map(
  Object.entries((scopeConstrainedRolesDoc as ScopeConstrainedRolesDoc).roles).map(([role, scopes]) => [
    role,
    new Set(scopes),
  ]),
);

/** Is a `role` grant at `scopeType` one that role's OWN derived-role condition in
 *  `derived_roles.yaml` can ever be satisfied by?
 *
 *  - `role` has NO entry in the map -> UNCONSTRAINED -> always `true` (fail-open; see module header).
 *  - `role` has an entry -> `true` iff `scopeType` is a member of that role's own reachable-scope set.
 *
 *  Note: this checks (role, scopeType) ONLY, never `scopeId` — matching the ticket's own filter unit
 *  ("the originating grant's (role, scopeType) pairing"). A grant at the RIGHT scopeType but the
 *  WRONG scopeId (e.g. `manager@company:someOtherCompany`) is a DIFFERENT, already-handled concern:
 *  every `perm_*` mirror's own `g.scopeId == request.resource.attr.tenantId` clause (or, for
 *  `org_unit_lead`, the `unitAncestors` containment check) already re-verifies scopeId per request —
 *  this function only needs to catch the case that check can never see, because it operates on a
 *  scopeType branch the mirror doesn't even test against for that role's shape. */
export function isGrantScopeReachable(role: string, scopeType: string): boolean {
  const allowed = SCOPE_CONSTRAINED_ROLES.get(role);
  return !allowed || allowed.has(scopeType);
}
