-- SM-20 — search-terms sync (docs/blueprints/seo-sem-design.md §12 SM-20; tracker §12 row: "Ads-
-- Scripts read bridge: exporter template + signed n8n webhook -> metrics-daily + search terms").
--
-- ── NUMBERING (migrations/README.md rule 5) ────────────────────────────────────────────────────────
-- `ls migrations | tail` at write time showed head = 0061_search_google_performance.sql, and the
-- README's own reservation note still holds 0058/0059 for TR-23/metric-seeds (neither landed as a
-- file on disk) — this migration does not touch those. Takes the next genuinely free number: 0062.
--
-- ── WHAT THIS IS ───────────────────────────────────────────────────────────────────────────────────
-- ONE new tenant-scoped table, `search_term_metrics_daily`, that the SM-20 webhook
-- (search.controller.ts's `POST search-terms/callback`, service layer in `sem-search-terms.ts`)
-- writes into. Grain: campaign x ad_group x date x term x match_type — the raw per-term row a
-- Google Ads "search terms" report emits, one row per distinct term/day/ad-group, NOT the coarser
-- campaign-level daily rollup `search_campaign_metrics_daily` (0034) already covers. The two tables
-- are deliberately separate: metrics-daily is a campaign x date aggregate (SM-18's own ingest target,
-- untouched by this ticket, which is scoped to the search-terms half of SM-20 only per the ticket
-- brief); this table is the finer per-term grain the "Search Terms" console tab (already listed in
-- the module's uiManifest) needs to render an actual list, and the input a future negative-keyword
-- sweep (SM-22) reads from.
--
-- ── WHY THIS IS NOT A PAID PULL, AND WHY THAT MATTERS TO THIS TABLE'S SHAPE ───────────────────────────
-- No provider is dispatched to produce this data — a client's own Google Ads Script (an exporter
-- template generated by this platform, seeded with OUR internal engagement/campaign ids) runs INSIDE
-- their Ads account and POSTs its own account's data to us. There is nothing to meter: no
-- `provider_call_id` FK to `search_provider_calls` (same reasoning 0061 gave for search_gsc_
-- performance/search_ga4_metrics — a third egress class, no vendor dollar of OURS to meter) and no
-- row here is ever created via `dispatchProviderOp`.
--
-- `cost_minor` on this table is a DIFFERENT kind of money than anything metered elsewhere in this
-- module (design addendum §A3 money-language rule, applied here): it is the CLIENT'S OWN real Google
-- Ads spend for that search term, self-reported by their account via the script they run — never our
-- cost-to-serve, never a projection, and must never be summed with `search_provider_calls.cost_usd`
-- or presented as "our" spend. See the column comment below and sem-search-terms.ts's file header.
--
-- ── IDEMPOTENCY: SCHEMA-LEVEL, HASH vs. TUPLE — THE TICKET'S OWN QUESTION, ANSWERED ───────────────────
-- The natural key is (campaign_id, ad_group_id, date, term, match_type). `term` is UNBOUNDED,
-- caller-supplied free text (an actual end-user search query, no fixed length Google itself
-- guarantees) — the same shape SM-08's `report_hash` and 0061's `search_gsc_performance.row_hash`
-- exist to solve, and for the identical reason: a raw multi-column UNIQUE including an unbounded text
-- column risks index-entry-size limits under a pathological value and, short of that, still bloats
-- the unique btree with full query strings. This table therefore takes SM-08's precedent (server-
-- computed sha256 hex over the canonical tuple, `row_hash`, computed in `sem-search-terms.ts`'s
-- `computeSearchTermRowHash`) — NOT 0061's `search_ga4_metrics` tuple-UNIQUE shape, because that
-- table's `channel_group` is GA4's own short bounded taxonomy and this one's `term` is not remotely
-- analogous. `UNIQUE (tenant_id, campaign_id, row_hash)` is what an `INSERT ... ON CONFLICT ... DO
-- UPDATE` resolves against in the ingest code — a schema-level guarantee, not application logic, and
-- (per 0061's own established point, restated here because it is the property this ticket's forced-
-- race test exists to prove) what makes a concurrent redelivery race resolve atomically at the index
-- rather than through an application check-then-insert window.
--
-- ── PROVENANCE: `simulated` FROM DAY ONE (§A4.7) ──────────────────────────────────────────────────────
-- This edge has neither a `DispatchResult` (no dispatch happens, see above) nor a per-connection
-- OAuth issuer-honesty flag (0060/0061's source, for a route that DOES carry a Google OAuth
-- connection) — this webhook is authenticated by a single shared secret, not a per-client OAuth
-- token, so neither existing `simulated` source applies verbatim. The equivalent signal THIS module
-- already uses for "is this environment producing real vendor-shaped data or demo data" absent any
-- connection/dispatch object is the platform-wide mode switch, `config.search.providerMode` (0047's
-- own file header: "...or while the platform ran in `simulate` mode"). `sem-search-terms.ts` reads it
-- once, fresh, at the moment of each ingest write (never cached, never re-derived later) and stamps
-- `simulated = (providerMode === 'simulate')` on every row that ingest call writes — matching 0047/
-- 0048/0060/0061's shared `NOT NULL DEFAULT false` law and its load-bearing reason: there are no
-- pre-existing rows in a brand-new table, but a nullable column would leave the first `WHERE
-- simulated = <mode>` reader written against this table exposed to the same UNKNOWN-in-a-predicate
-- fail-open the whole §A4.7 rule exists to foreclose.
--
-- ── HOSTILE-INPUT BOUNDS (design addendum §A14 hazard: a hostile payload must 400, never 500) ────────
-- Row-count and term-length ceilings are enforced in `sem-search-terms.ts`'s `validateSearchTermBatch`
-- (application-level, so a malformed/oversized POST body never reaches a query at all — SM-08's own
-- "validation throws before the transaction opens" discipline); the CHECK constraints below are a
-- second, schema-level backstop against a negative count ever being written by any FUTURE caller of
-- this table this migration cannot foresee (defense in depth, not a duplicate of the app-level guard).
--
-- ── RLS ────────────────────────────────────────────────────────────────────────────────────────────
-- FORCE ROW LEVEL SECURITY + 0034's byte-identical composed policy
-- (tenant_id = ANY(app_current_tenants()) AND app_module_allowed('search')) — the same shape every
-- other tenant-scoped search_* table uses, so this client-attributed data is no more reachable than
-- any sibling row.
--
-- ── NO DML ─────────────────────────────────────────────────────────────────────────────────────────
-- CREATE-only: no UPDATE, no DELETE, no INSERT...SELECT, no backfill — nothing to backfill, this
-- table can only be populated by code that does not exist before this migration. Runtime DML grants
-- come from the owner's ALTER DEFAULT PRIVILEGES + RUNTIME_GRANTS_SQL pass (migrations/README.md); no
-- in-migration GRANTs.

CREATE TABLE search_term_metrics_daily (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES companies(id),
  campaign_id uuid NOT NULL REFERENCES search_campaigns(id),
  ad_group_id uuid NOT NULL REFERENCES search_ad_groups(id),
  date date NOT NULL,
  term text NOT NULL,
  match_type text NOT NULL DEFAULT 'none' CHECK (match_type IN ('broad', 'phrase', 'exact', 'none')),
  impressions bigint NOT NULL DEFAULT 0 CHECK (impressions >= 0),
  clicks bigint NOT NULL DEFAULT 0 CHECK (clicks >= 0),
  -- The CLIENT'S OWN real Google Ads spend for this term, as reported by their account (see the file
  -- header's money-language note) — NEVER our metered provider cost, NEVER a projection, and never to
  -- be summed with search_provider_calls.cost_usd.
  cost_minor bigint NOT NULL DEFAULT 0 CHECK (cost_minor >= 0),
  currency text,
  conversions numeric NOT NULL DEFAULT 0 CHECK (conversions >= 0),
  conv_value_minor bigint NOT NULL DEFAULT 0 CHECK (conv_value_minor >= 0),
  -- The idempotency key (see file header). sha256 hex of the canonical
  -- campaign_id|ad_group_id|date|term|match_type tuple, computed in sem-search-terms.ts's
  -- computeSearchTermRowHash — never guessed here.
  row_hash text NOT NULL,
  simulated boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'ads_scripts',
  origin_site text NOT NULL DEFAULT 'central',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, campaign_id, row_hash)
);
CREATE INDEX ix_search_term_metrics_daily_campaign ON search_term_metrics_daily (tenant_id, campaign_id, date DESC);
CREATE INDEX ix_search_term_metrics_daily_ad_group ON search_term_metrics_daily (tenant_id, ad_group_id, date DESC);

ALTER TABLE search_term_metrics_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_term_metrics_daily FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON search_term_metrics_daily;
CREATE POLICY tenant_isolation ON search_term_metrics_daily FOR ALL
  USING (tenant_id = ANY(app_current_tenants()) AND app_module_allowed('search'))
  WITH CHECK (tenant_id = ANY(app_current_tenants()) AND app_module_allowed('search'));

COMMENT ON TABLE search_term_metrics_daily IS
  'SM-20 — per-term daily performance rows from the Ads-Scripts search-terms webhook (design §12 '
  'SM-20). Grain: campaign x ad_group x date x term x match_type. NEVER search_provider_calls (no '
  'vendor dollar of OURS to meter — this is the CLIENT''s own Google Ads spend, self-reported). '
  'Idempotent via UNIQUE (tenant_id, campaign_id, row_hash), a server-computed content hash (SM-08''s '
  'precedent, chosen over a tuple UNIQUE because term is unbounded caller text) — enforced at the '
  'index under INSERT...ON CONFLICT, so a concurrent redelivery race resolves atomically rather than '
  'duplicating rows. simulated stamped from config.search.providerMode at write time (§A4.7), since '
  'this edge has neither a DispatchResult nor a per-connection OAuth issuer flag to draw from.';

COMMENT ON COLUMN search_term_metrics_daily.cost_minor IS
  'The CLIENT''s own real Google Ads spend for this term, as reported by their account via the '
  'Ads Script (design addendum §A3 money-language rule) — NOT our metered provider cost '
  '(search_provider_calls.cost_usd), NOT a projection. Never sum with either.';

COMMENT ON COLUMN search_term_metrics_daily.row_hash IS
  'sha256 hex of the canonical campaign_id|ad_group_id|date|term|match_type tuple '
  '(sem-search-terms.ts computeSearchTermRowHash). THE idempotency key — the UNIQUE (tenant_id, '
  'campaign_id, row_hash) constraint is what makes a concurrent redelivery race-safe; term is kept as '
  'its own column for readable filtering only and is never itself relied on for uniqueness (it is '
  'unbounded-length caller text).';

COMMENT ON COLUMN search_term_metrics_daily.simulated IS
  'true = this row was ingested while config.search.providerMode = ''simulate'', stamped at the SAME '
  'INSERT as the row''s payload, never re-derived later. NOT NULL DEFAULT false: load-bearing for the '
  'same reason as every prior provenance column in this module (0047/0048/0060/0061) — an '
  'UNKNOWN-in-a-WHERE-clause is a fail-open the instant any reader ever filters on this column.';
