-- 0094_iam_02a_role_permission_bundles.sql — IAM-02a: seed every built-in role as a permission
-- bundle in the (until 0093, dead) `role_permissions` table.
--
-- ── SOURCE OF TRUTH AND METHOD ───────────────────────────────────────────────────────────────────
-- Bundles are derived from the ACTUAL Cerbos policies (`cerbos/policies/resource_*.yaml` +
-- `derived_roles.yaml`), not from `platform-ui/src/lib/rbac.ts`. Every resource-policy rule was
-- parsed (real YAML parse, not regex) and `*` actions were wildcard-expanded against each kind's
-- own full action set (`permission-catalog.json`'s 230 concrete `(cerbosKind, cerbosAction)`
-- pairs — the same universe IAM-01b/01c already froze). A role "reaches" a pair if ANY allow rule
-- names it (directly, or via the module-string-composition / it_staff / hr_people_* groupings
-- below) for that action — the same "can this role reach this action in principle" abstraction
-- `docs/superpowers/plans/2026-08-10-iam-01a-02a-analysis.md` Part 4 and the drift register both
-- use (resource-instance conditions — inTenant, notLow/assurance, self-ownership — are treated as
-- "the request satisfies them", exactly like the prior analyses; that is why `member`'s count below
-- includes self-scoped actions such as `hr.case.create`/`hr.case.cancel` and `reports.appraisal.ack`
-- alongside its unconditional ones). Independently cross-checked against every published number in
-- the analysis doc's Part 4 table (platform_admin 215/57, company_admin 199/55, group_executive
-- 118/35, manager 109, member 74, team_lead 60, viewer 30, client 6, it_staff 3, module_approver 1,
-- hr_people_ops 5, hr_people_reader 5, module_staff 34, module_manager 56) — every one reproduced
-- exactly. class='relationship' permissions (the 15 assistant/mcp_tool exemptions, Ruling 3) are
-- NEVER inserted into any bundle below, and 0093's `role_permissions_reject_relationship` trigger
-- enforces that at the DB layer even if this file's own SELECT ever tried to (it does not).
--
-- ── COUPLING WITH 0093 (IAM-01c) ─────────────────────────────────────────────────────────────────
-- This file does not read or duplicate 0093_iam_permission_catalog.sql's own DDL/DML — it only
-- depends on the CONTRACT that migration establishes: `permissions.key` populated 1:1 from
-- `permission-catalog.json`. Every bundle row below is inserted by JOINing on `permissions.key`,
-- so a typo'd key here simply fails to join (caught by the per-role count assertions at the bottom,
-- not assumed away).
--
-- ── MODULE-COMPOSED ROLES: RESOLVING `module_staff`/`module_manager`/`module_approver` ───────────
-- `derived_roles.yaml` string-composes these three from `resource.attr.module` at request time
-- (Ruling 5's WSD-2 trick), so a policy file alone never names a concrete role. Resolved here by
-- reading which `module:` attribute value each resource kind's callers actually pass (grepped
-- controllers, not assumed):
--   hr_case, hr_record                              -> module "hr"      (module_staff=hr_staff, module_manager=hr_manager)
--   resource_search_{property,campaign,engagement,   -> module "search"  (module_staff=search_staff, module_manager=search_manager)
--     keyword,ledger,audit,report}
--   report_document (module_staff/manager rule ONLY  -> module "reports" (module_staff=reports_staff, module_manager=reports_manager)
--     — its own condition hardcodes `attr.module == "reports"`, verified by direct read)
--   automation_approval (module_manager rule ONLY    -> module "hr" ONLY, hardcoded in the rule's own
--     — hardcodes `attr.module == "hr"` in the rule           condition, NOT resource-generic — a
--       condition itself, verified by direct read)             first parser pass over-attributed this
--                                                                to search_manager/reports_manager; the
--                                                                drift register's own §0 correction
--                                                                flags the identical mistake, confirmed
--                                                                independently here.
--   service_assignment (`read`), member (`read`)     -> GENERIC (no module hardcode in the rule) —
--     any module_staff/module_manager-composed role reaches these for its own module's context
--     (service_assignment's own `module_key` attribute; member's `?module=` query passthrough,
--     `core.controller.ts`'s WSD-4 comment). Bundled onto ALL THREE currently-seeded module_staff/
--     module_manager pairs (hr_*, search_*, reports_*).
--   webdev_change_request, webdev_provisioned_site   -> module "webdev" — but NO `webdev_staff`/
--     (module_staff AND module_manager rules present)   `webdev_manager` role exists in the `roles`
--                                                        table (no migration, no seed script seeds
--                                                        them). These 7 (kind,action) pairs are real
--                                                        Cerbos reach for module_staff/module_manager
--                                                        but currently UNCLAIMABLE by any real role —
--                                                        flagged as a NEW provisioning gap (sibling to
--                                                        IAM-02d/0091's search_staff/search_manager
--                                                        finding and IAM-02e/0095's baseline-role
--                                                        finding), NOT fixed here (out of this
--                                                        ticket's remit — no ticket authorizes minting
--                                                        a `webdev_staff`/`webdev_manager` role).
--   module_approver                                  -> the only live instance is `agency_approval`
--     (agency_approval:approve only)                    (module "agency") -> real role `agency_approver`.
--
-- ── ROLE ROWS THIS FILE MUST SELF-SEED (idempotent, same idiom as 0026/0069/0072/0091/0095) ──────
-- role_permissions needs a role_id, and this migration (0094) runs BEFORE 0095 in filename order —
-- so IAM-02e's six baseline roles (member/manager/company_admin/platform_admin/group_executive/
-- it_admin) do NOT exist yet at the point this file executes on a fresh, migration-only database.
-- Depending on 0095 having already run would be an ordering assumption this repo has been burned by
-- before (migration-idioms-that-lie); instead this file guarantees its own dependency, using the
-- IDENTICAL `INSERT ... SELECT ... WHERE NOT EXISTS` idiom already established by every prior
-- role-seeding migration (backed by 0073's `roles_global_name_uniq` partial index, so this is safe
-- to run whether or not 0095 has landed, and 0095 landing afterward is a harmless no-op against the
-- same guard). `hr_staff`/`hr_manager` (0026), `reports_staff`/`reports_manager` (0069), `client`
-- (0072), and `team_lead`/`viewer`/`it_manager`/`it`/`search_staff`/`search_manager` (0091) are all
-- numerically BEFORE 0094 and therefore guaranteed already present — not re-seeded here.
-- `agency_approver` is a SEPARATE, NEW finding: no migration ANYWHERE seeds it (confirmed by
-- grepping every `migrations/*.sql` for the literal string) — it has existed, live, on
-- gda-aicenter ONLY because `npm run seed:agency` created it by hand. That is the exact same
-- provisioning-gap shape 0095's own header describes for the six baseline roles, just not counted
-- in that ticket's list of six. Seeded here because this migration is what first needs the row to
-- exist for a real, live-held role (drift register finding #1) — not a scope grab on IAM-02e; noted
-- for a follow-up ticket in this ticket's own report.
INSERT INTO roles (id, company_id, name, description)
SELECT gen_random_uuid(), NULL, r.name, r.description
FROM (VALUES
  ('platform_admin',   'Global superadmin — the platform-wide Cerbos wildcard (''*'') bypass rule present on ~57 of 61 resource kinds (215/230 concrete pairs; the 15 relationship-class exemptions are bypass-exempt by design, Ruling 3).'),
  ('company_admin',    'Company-scoped administrator — near-universal reach within one company (199/230 pairs, 55/61 kinds); does not span companies.'),
  ('group_executive',  'Global cross-company executive — narrower than company_admin in enforcement (118/230 pairs, 35/61 kinds); several deliberate Cerbos exclusions vs the rbac.ts ''ALL'' mirror (D-7, IAM phase 1) are documented, not fixed, here.'),
  ('manager',          'Company-scoped operational lead (109/230 pairs, 41/61 kinds); excluded from cross-cutting approval decisions Cerbos reserves for company_admin/group_executive/module_manager/module_approver (DR-1).'),
  ('member',           'Baseline company-scoped contributor (74/230 pairs, 34/61 kinds, incl. self-scoped actions like hr.case.create/cancel).'),
  ('it_admin',         'Company-scoped IT operator tier — identical Cerbos reach to it_manager/it (resource_device.yaml is the only policy reading any of the three; 3/230 pairs).')
) AS r(name, description)
WHERE NOT EXISTS (
  SELECT 1 FROM roles WHERE company_id IS NULL AND name = r.name
);

INSERT INTO roles (id, company_id, name, description)
SELECT gen_random_uuid(), NULL, 'agency_approver',
  'agency module_approver (WSD-2) — approves agency_approval requests (1/230 pairs). NEW FINDING (IAM-02a): no migration has ever seeded this role; it has existed live ONLY via the manual seed:agency script (drift-register finding #1''s single live holder). Same provisioning-gap shape as IAM-02e''s six baseline roles, seeded here because role_permissions needs the row.'
WHERE NOT EXISTS (
  SELECT 1 FROM roles WHERE company_id IS NULL AND name = 'agency_approver'
);

-- ── The bundles ───────────────────────────────────────────────────────────────────────────────────
-- 925 (role, permission-key) pairs across 18 roles. `ON CONFLICT DO NOTHING` on the existing
-- `role_permissions` PK (role_id, permission_id) makes this idempotent/re-runnable. Every key below
-- must resolve via `permissions.key` (0093) and every role name via `roles.name` (above, or an
-- earlier migration) — a typo in either silently drops that one row from the JOIN rather than
-- erroring, which is exactly why the assertions below check per-role COUNTS rather than trusting
-- "the INSERT ran without error".
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
  ('platform_admin', 'agency.approval.approve'),
  ('platform_admin', 'agency.approval.create'),
  ('platform_admin', 'agency.approval.read'),
  ('platform_admin', 'agency.brief.create'),
  ('platform_admin', 'agency.brief.delete'),
  ('platform_admin', 'agency.brief.read'),
  ('platform_admin', 'agency.brief.update'),
  ('platform_admin', 'agency.campaign.create'),
  ('platform_admin', 'agency.campaign.delete'),
  ('platform_admin', 'agency.campaign.read'),
  ('platform_admin', 'agency.campaign.update'),
  ('platform_admin', 'agency.creative_asset.create'),
  ('platform_admin', 'agency.creative_asset.delete'),
  ('platform_admin', 'agency.creative_asset.read'),
  ('platform_admin', 'agency.creative_asset.update'),
  ('platform_admin', 'billing.invoice.create'),
  ('platform_admin', 'billing.invoice.delete'),
  ('platform_admin', 'billing.invoice.read'),
  ('platform_admin', 'billing.invoice.update'),
  ('platform_admin', 'core.activity.read'),
  ('platform_admin', 'core.automation_approval.create'),
  ('platform_admin', 'core.automation_approval.decide'),
  ('platform_admin', 'core.automation_approval.read'),
  ('platform_admin', 'core.automation_approval.retry'),
  ('platform_admin', 'core.chat_group.add_member'),
  ('platform_admin', 'core.chat_group.pin'),
  ('platform_admin', 'core.chat_group.promote_member'),
  ('platform_admin', 'core.chat_group.remove_member'),
  ('platform_admin', 'core.chat_group.set_subject'),
  ('platform_admin', 'core.client.create'),
  ('platform_admin', 'core.client.delete'),
  ('platform_admin', 'core.client.read'),
  ('platform_admin', 'core.client.update'),
  ('platform_admin', 'core.client_contact.create'),
  ('platform_admin', 'core.client_contact.read'),
  ('platform_admin', 'core.client_contact.revoke'),
  ('platform_admin', 'core.client_contact.update'),
  ('platform_admin', 'core.comment.create'),
  ('platform_admin', 'core.comment.read'),
  ('platform_admin', 'core.company.delete'),
  ('platform_admin', 'core.company.read'),
  ('platform_admin', 'core.company.update'),
  ('platform_admin', 'core.compliance_gate.read'),
  ('platform_admin', 'core.compliance_gate.update'),
  ('platform_admin', 'core.contract.create'),
  ('platform_admin', 'core.contract.delete'),
  ('platform_admin', 'core.contract.read'),
  ('platform_admin', 'core.contract.send'),
  ('platform_admin', 'core.contract.update'),
  ('platform_admin', 'core.custom_field.create'),
  ('platform_admin', 'core.custom_field.delete'),
  ('platform_admin', 'core.custom_field.read'),
  ('platform_admin', 'core.custom_field.update'),
  ('platform_admin', 'core.deliverable.create'),
  ('platform_admin', 'core.deliverable.delete'),
  ('platform_admin', 'core.deliverable.read'),
  ('platform_admin', 'core.deliverable.update'),
  ('platform_admin', 'core.file.create'),
  ('platform_admin', 'core.file.delete'),
  ('platform_admin', 'core.file.read'),
  ('platform_admin', 'core.identity_link.delete'),
  ('platform_admin', 'core.identity_link.read'),
  ('platform_admin', 'core.identity_link.update'),
  ('platform_admin', 'core.integration_connection.create'),
  ('platform_admin', 'core.integration_connection.delete'),
  ('platform_admin', 'core.integration_connection.read'),
  ('platform_admin', 'core.integration_connection.update'),
  ('platform_admin', 'core.meeting_recording.create'),
  ('platform_admin', 'core.meeting_recording.ingest'),
  ('platform_admin', 'core.meeting_recording.read'),
  ('platform_admin', 'core.meeting_recording.relink'),
  ('platform_admin', 'core.meeting_recording.sync_drive'),
  ('platform_admin', 'core.meeting_recording.update'),
  ('platform_admin', 'core.member.read'),
  ('platform_admin', 'core.notification.create'),
  ('platform_admin', 'core.notification.read'),
  ('platform_admin', 'core.notification.update'),
  ('platform_admin', 'core.org_structure.read'),
  ('platform_admin', 'core.org_structure.update'),
  ('platform_admin', 'core.pipeline_gate.create'),
  ('platform_admin', 'core.pipeline_gate.decide'),
  ('platform_admin', 'core.pipeline_gate.read'),
  ('platform_admin', 'core.pipeline_run.create'),
  ('platform_admin', 'core.pipeline_run.read'),
  ('platform_admin', 'core.pipeline_run.update'),
  ('platform_admin', 'core.pipeline_stage.create'),
  ('platform_admin', 'core.pipeline_stage.read'),
  ('platform_admin', 'core.pipeline_stage.update'),
  ('platform_admin', 'core.project.create'),
  ('platform_admin', 'core.project.delete'),
  ('platform_admin', 'core.project.read'),
  ('platform_admin', 'core.project.update'),
  ('platform_admin', 'core.rollup.read'),
  ('platform_admin', 'core.rollup_recompute.create'),
  ('platform_admin', 'core.scope_signoff.create'),
  ('platform_admin', 'core.scope_signoff.read'),
  ('platform_admin', 'core.service_assignment.accept'),
  ('platform_admin', 'core.service_assignment.propose'),
  ('platform_admin', 'core.service_assignment.read'),
  ('platform_admin', 'core.service_assignment.reconcile'),
  ('platform_admin', 'core.service_assignment.relink'),
  ('platform_admin', 'core.service_assignment.resume'),
  ('platform_admin', 'core.service_assignment.revoke'),
  ('platform_admin', 'core.service_assignment.suspend'),
  ('platform_admin', 'core.task.create'),
  ('platform_admin', 'core.task.delete'),
  ('platform_admin', 'core.task.read'),
  ('platform_admin', 'core.task.update'),
  ('platform_admin', 'core.team.create'),
  ('platform_admin', 'core.team.delete'),
  ('platform_admin', 'core.team.read'),
  ('platform_admin', 'core.team.update'),
  ('platform_admin', 'core.time_entry.create'),
  ('platform_admin', 'core.time_entry.delete'),
  ('platform_admin', 'core.time_entry.read'),
  ('platform_admin', 'core.time_entry.update'),
  ('platform_admin', 'core.user.create'),
  ('platform_admin', 'core.user.delete'),
  ('platform_admin', 'core.user.read'),
  ('platform_admin', 'core.user.update'),
  ('platform_admin', 'core.work_activity.create'),
  ('platform_admin', 'core.work_activity.read'),
  ('platform_admin', 'hr.case.cancel'),
  ('platform_admin', 'hr.case.create'),
  ('platform_admin', 'hr.case.delete'),
  ('platform_admin', 'hr.case.export'),
  ('platform_admin', 'hr.case.read'),
  ('platform_admin', 'hr.case.update'),
  ('platform_admin', 'hr.record.create'),
  ('platform_admin', 'hr.record.delete'),
  ('platform_admin', 'hr.record.export'),
  ('platform_admin', 'hr.record.read'),
  ('platform_admin', 'hr.record.update'),
  ('platform_admin', 'it.device.create'),
  ('platform_admin', 'it.device.delete'),
  ('platform_admin', 'it.device.read'),
  ('platform_admin', 'it.device.update'),
  ('platform_admin', 'knowledge.source.read'),
  ('platform_admin', 'knowledge.source.update'),
  ('platform_admin', 'pm.project.manage'),
  ('platform_admin', 'pm.project.read'),
  ('platform_admin', 'pm.task.create'),
  ('platform_admin', 'pm.task.delete'),
  ('platform_admin', 'pm.task.manage'),
  ('platform_admin', 'pm.task.read'),
  ('platform_admin', 'pm.task.update'),
  ('platform_admin', 'portal.decide'),
  ('platform_admin', 'portal.pay'),
  ('platform_admin', 'portal.read'),
  ('platform_admin', 'portal.request_change'),
  ('platform_admin', 'portal.sign'),
  ('platform_admin', 'portal.update_profile'),
  ('platform_admin', 'reports.admin.recompute'),
  ('platform_admin', 'reports.appraisal.ack'),
  ('platform_admin', 'reports.appraisal.confirm_evidence'),
  ('platform_admin', 'reports.appraisal.cycle_admin'),
  ('platform_admin', 'reports.appraisal.finalize'),
  ('platform_admin', 'reports.appraisal.read'),
  ('platform_admin', 'reports.appraisal.submit'),
  ('platform_admin', 'reports.appraisal.write'),
  ('platform_admin', 'reports.checkin.excuse'),
  ('platform_admin', 'reports.checkin.missed_by_unit'),
  ('platform_admin', 'reports.checkin.pending_reminders'),
  ('platform_admin', 'reports.checkin.read'),
  ('platform_admin', 'reports.checkin.submit'),
  ('platform_admin', 'reports.document.read_company'),
  ('platform_admin', 'reports.document.read_department'),
  ('platform_admin', 'reports.document.read_person'),
  ('platform_admin', 'reports.document.read_project'),
  ('platform_admin', 'reports.period.amend'),
  ('platform_admin', 'reports.period.pin'),
  ('platform_admin', 'reports.period.seal'),
  ('platform_admin', 'reports.period.view'),
  ('platform_admin', 'search.audit.create'),
  ('platform_admin', 'search.audit.delete'),
  ('platform_admin', 'search.audit.read'),
  ('platform_admin', 'search.audit.run'),
  ('platform_admin', 'search.audit.update'),
  ('platform_admin', 'search.campaign.apply_manual'),
  ('platform_admin', 'search.campaign.apply_negatives'),
  ('platform_admin', 'search.campaign.create'),
  ('platform_admin', 'search.campaign.delete'),
  ('platform_admin', 'search.campaign.launch'),
  ('platform_admin', 'search.campaign.propose_change'),
  ('platform_admin', 'search.campaign.read'),
  ('platform_admin', 'search.campaign.set_budget'),
  ('platform_admin', 'search.campaign.update'),
  ('platform_admin', 'search.engagement.create'),
  ('platform_admin', 'search.engagement.delete'),
  ('platform_admin', 'search.engagement.read'),
  ('platform_admin', 'search.engagement.set_scope'),
  ('platform_admin', 'search.engagement.update'),
  ('platform_admin', 'search.keyword.create'),
  ('platform_admin', 'search.keyword.delete'),
  ('platform_admin', 'search.keyword.read'),
  ('platform_admin', 'search.keyword.research'),
  ('platform_admin', 'search.keyword.update'),
  ('platform_admin', 'search.ledger.admin'),
  ('platform_admin', 'search.ledger.read'),
  ('platform_admin', 'search.property.create'),
  ('platform_admin', 'search.property.delete'),
  ('platform_admin', 'search.property.read'),
  ('platform_admin', 'search.property.update'),
  ('platform_admin', 'search.report.approve'),
  ('platform_admin', 'search.report.create'),
  ('platform_admin', 'search.report.delete'),
  ('platform_admin', 'search.report.deliver'),
  ('platform_admin', 'search.report.read'),
  ('platform_admin', 'search.report.update'),
  ('platform_admin', 'webdev.change_request.create'),
  ('platform_admin', 'webdev.change_request.read'),
  ('platform_admin', 'webdev.change_request.triage'),
  ('platform_admin', 'webdev.provisioned_site.provision'),
  ('platform_admin', 'webdev.provisioned_site.read'),
  ('platform_admin', 'webdev.provisioned_site.reconcile'),
  ('company_admin', 'agency.approval.approve'),
  ('company_admin', 'agency.approval.create'),
  ('company_admin', 'agency.approval.read'),
  ('company_admin', 'agency.brief.create'),
  ('company_admin', 'agency.brief.delete'),
  ('company_admin', 'agency.brief.read'),
  ('company_admin', 'agency.brief.update'),
  ('company_admin', 'agency.campaign.create'),
  ('company_admin', 'agency.campaign.delete'),
  ('company_admin', 'agency.campaign.read'),
  ('company_admin', 'agency.campaign.update'),
  ('company_admin', 'agency.creative_asset.create'),
  ('company_admin', 'agency.creative_asset.delete'),
  ('company_admin', 'agency.creative_asset.read'),
  ('company_admin', 'agency.creative_asset.update'),
  ('company_admin', 'billing.invoice.create'),
  ('company_admin', 'billing.invoice.delete'),
  ('company_admin', 'billing.invoice.read'),
  ('company_admin', 'billing.invoice.update'),
  ('company_admin', 'core.activity.read'),
  ('company_admin', 'core.automation_approval.create'),
  ('company_admin', 'core.automation_approval.decide'),
  ('company_admin', 'core.automation_approval.read'),
  ('company_admin', 'core.automation_approval.retry'),
  ('company_admin', 'core.chat_group.add_member'),
  ('company_admin', 'core.chat_group.pin'),
  ('company_admin', 'core.chat_group.promote_member'),
  ('company_admin', 'core.chat_group.remove_member'),
  ('company_admin', 'core.chat_group.set_subject'),
  ('company_admin', 'core.client.create'),
  ('company_admin', 'core.client.delete'),
  ('company_admin', 'core.client.read'),
  ('company_admin', 'core.client.update'),
  ('company_admin', 'core.client_contact.create'),
  ('company_admin', 'core.client_contact.read'),
  ('company_admin', 'core.client_contact.revoke'),
  ('company_admin', 'core.client_contact.update'),
  ('company_admin', 'core.comment.create'),
  ('company_admin', 'core.comment.read'),
  ('company_admin', 'core.company.delete'),
  ('company_admin', 'core.company.read'),
  ('company_admin', 'core.company.update'),
  ('company_admin', 'core.compliance_gate.read'),
  ('company_admin', 'core.compliance_gate.update'),
  ('company_admin', 'core.contract.create'),
  ('company_admin', 'core.contract.delete'),
  ('company_admin', 'core.contract.read'),
  ('company_admin', 'core.contract.send'),
  ('company_admin', 'core.contract.update'),
  ('company_admin', 'core.custom_field.create'),
  ('company_admin', 'core.custom_field.delete'),
  ('company_admin', 'core.custom_field.read'),
  ('company_admin', 'core.custom_field.update'),
  ('company_admin', 'core.deliverable.create'),
  ('company_admin', 'core.deliverable.delete'),
  ('company_admin', 'core.deliverable.read'),
  ('company_admin', 'core.deliverable.update'),
  ('company_admin', 'core.file.create'),
  ('company_admin', 'core.file.delete'),
  ('company_admin', 'core.file.read'),
  ('company_admin', 'core.identity_link.delete'),
  ('company_admin', 'core.identity_link.read'),
  ('company_admin', 'core.identity_link.update'),
  ('company_admin', 'core.integration_connection.create'),
  ('company_admin', 'core.integration_connection.delete'),
  ('company_admin', 'core.integration_connection.read'),
  ('company_admin', 'core.integration_connection.update'),
  ('company_admin', 'core.meeting_recording.create'),
  ('company_admin', 'core.meeting_recording.ingest'),
  ('company_admin', 'core.meeting_recording.read'),
  ('company_admin', 'core.meeting_recording.relink'),
  ('company_admin', 'core.meeting_recording.sync_drive'),
  ('company_admin', 'core.meeting_recording.update'),
  ('company_admin', 'core.member.read'),
  ('company_admin', 'core.notification.create'),
  ('company_admin', 'core.notification.read'),
  ('company_admin', 'core.notification.update'),
  ('company_admin', 'core.org_structure.read'),
  ('company_admin', 'core.org_structure.update'),
  ('company_admin', 'core.pipeline_gate.create'),
  ('company_admin', 'core.pipeline_gate.decide'),
  ('company_admin', 'core.pipeline_gate.read'),
  ('company_admin', 'core.pipeline_run.create'),
  ('company_admin', 'core.pipeline_run.read'),
  ('company_admin', 'core.pipeline_run.update'),
  ('company_admin', 'core.pipeline_stage.create'),
  ('company_admin', 'core.pipeline_stage.read'),
  ('company_admin', 'core.pipeline_stage.update'),
  ('company_admin', 'core.project.create'),
  ('company_admin', 'core.project.delete'),
  ('company_admin', 'core.project.read'),
  ('company_admin', 'core.project.update'),
  ('company_admin', 'core.rollup_recompute.create'),
  ('company_admin', 'core.scope_signoff.create'),
  ('company_admin', 'core.scope_signoff.read'),
  ('company_admin', 'core.service_assignment.accept'),
  ('company_admin', 'core.service_assignment.propose'),
  ('company_admin', 'core.service_assignment.read'),
  ('company_admin', 'core.service_assignment.relink'),
  ('company_admin', 'core.service_assignment.resume'),
  ('company_admin', 'core.service_assignment.revoke'),
  ('company_admin', 'core.service_assignment.suspend'),
  ('company_admin', 'core.task.create'),
  ('company_admin', 'core.task.delete'),
  ('company_admin', 'core.task.read'),
  ('company_admin', 'core.task.update'),
  ('company_admin', 'core.team.create'),
  ('company_admin', 'core.team.delete'),
  ('company_admin', 'core.team.read'),
  ('company_admin', 'core.team.update'),
  ('company_admin', 'core.time_entry.create'),
  ('company_admin', 'core.time_entry.delete'),
  ('company_admin', 'core.time_entry.read'),
  ('company_admin', 'core.time_entry.update'),
  ('company_admin', 'core.user.create'),
  ('company_admin', 'core.user.delete'),
  ('company_admin', 'core.user.read'),
  ('company_admin', 'core.user.update'),
  ('company_admin', 'core.work_activity.create'),
  ('company_admin', 'core.work_activity.read'),
  ('company_admin', 'hr.case.create'),
  ('company_admin', 'hr.case.delete'),
  ('company_admin', 'hr.case.export'),
  ('company_admin', 'hr.case.read'),
  ('company_admin', 'hr.case.update'),
  ('company_admin', 'hr.record.create'),
  ('company_admin', 'hr.record.delete'),
  ('company_admin', 'hr.record.export'),
  ('company_admin', 'hr.record.read'),
  ('company_admin', 'hr.record.update'),
  ('company_admin', 'it.device.create'),
  ('company_admin', 'it.device.delete'),
  ('company_admin', 'it.device.read'),
  ('company_admin', 'it.device.update'),
  ('company_admin', 'knowledge.source.read'),
  ('company_admin', 'knowledge.source.update'),
  ('company_admin', 'pm.project.manage'),
  ('company_admin', 'pm.project.read'),
  ('company_admin', 'pm.task.create'),
  ('company_admin', 'pm.task.delete'),
  ('company_admin', 'pm.task.manage'),
  ('company_admin', 'pm.task.read'),
  ('company_admin', 'pm.task.update'),
  ('company_admin', 'portal.read'),
  ('company_admin', 'reports.admin.recompute'),
  ('company_admin', 'reports.checkin.excuse'),
  ('company_admin', 'reports.checkin.missed_by_unit'),
  ('company_admin', 'reports.checkin.pending_reminders'),
  ('company_admin', 'reports.checkin.read'),
  ('company_admin', 'reports.document.read_company'),
  ('company_admin', 'reports.document.read_department'),
  ('company_admin', 'reports.document.read_person'),
  ('company_admin', 'reports.document.read_project'),
  ('company_admin', 'reports.period.amend'),
  ('company_admin', 'reports.period.pin'),
  ('company_admin', 'reports.period.seal'),
  ('company_admin', 'reports.period.view'),
  ('company_admin', 'search.audit.create'),
  ('company_admin', 'search.audit.delete'),
  ('company_admin', 'search.audit.read'),
  ('company_admin', 'search.audit.run'),
  ('company_admin', 'search.audit.update'),
  ('company_admin', 'search.campaign.apply_manual'),
  ('company_admin', 'search.campaign.apply_negatives'),
  ('company_admin', 'search.campaign.create'),
  ('company_admin', 'search.campaign.delete'),
  ('company_admin', 'search.campaign.launch'),
  ('company_admin', 'search.campaign.propose_change'),
  ('company_admin', 'search.campaign.read'),
  ('company_admin', 'search.campaign.set_budget'),
  ('company_admin', 'search.campaign.update'),
  ('company_admin', 'search.engagement.create'),
  ('company_admin', 'search.engagement.delete'),
  ('company_admin', 'search.engagement.read'),
  ('company_admin', 'search.engagement.set_scope'),
  ('company_admin', 'search.engagement.update'),
  ('company_admin', 'search.keyword.create'),
  ('company_admin', 'search.keyword.delete'),
  ('company_admin', 'search.keyword.read'),
  ('company_admin', 'search.keyword.research'),
  ('company_admin', 'search.keyword.update'),
  ('company_admin', 'search.ledger.admin'),
  ('company_admin', 'search.ledger.read'),
  ('company_admin', 'search.property.create'),
  ('company_admin', 'search.property.delete'),
  ('company_admin', 'search.property.read'),
  ('company_admin', 'search.property.update'),
  ('company_admin', 'search.report.approve'),
  ('company_admin', 'search.report.create'),
  ('company_admin', 'search.report.delete'),
  ('company_admin', 'search.report.deliver'),
  ('company_admin', 'search.report.read'),
  ('company_admin', 'search.report.update'),
  ('company_admin', 'webdev.change_request.create'),
  ('company_admin', 'webdev.change_request.read'),
  ('company_admin', 'webdev.change_request.triage'),
  ('company_admin', 'webdev.provisioned_site.provision'),
  ('company_admin', 'webdev.provisioned_site.read'),
  ('company_admin', 'webdev.provisioned_site.reconcile'),
  ('group_executive', 'billing.invoice.create'),
  ('group_executive', 'billing.invoice.delete'),
  ('group_executive', 'billing.invoice.read'),
  ('group_executive', 'billing.invoice.update'),
  ('group_executive', 'core.automation_approval.decide'),
  ('group_executive', 'core.automation_approval.read'),
  ('group_executive', 'core.automation_approval.retry'),
  ('group_executive', 'core.client_contact.create'),
  ('group_executive', 'core.client_contact.read'),
  ('group_executive', 'core.client_contact.revoke'),
  ('group_executive', 'core.client_contact.update'),
  ('group_executive', 'core.company.delete'),
  ('group_executive', 'core.company.read'),
  ('group_executive', 'core.company.update'),
  ('group_executive', 'core.compliance_gate.read'),
  ('group_executive', 'core.compliance_gate.update'),
  ('group_executive', 'core.contract.create'),
  ('group_executive', 'core.contract.delete'),
  ('group_executive', 'core.contract.read'),
  ('group_executive', 'core.contract.send'),
  ('group_executive', 'core.contract.update'),
  ('group_executive', 'core.integration_connection.create'),
  ('group_executive', 'core.integration_connection.delete'),
  ('group_executive', 'core.integration_connection.read'),
  ('group_executive', 'core.integration_connection.update'),
  ('group_executive', 'core.org_structure.read'),
  ('group_executive', 'core.org_structure.update'),
  ('group_executive', 'core.pipeline_gate.decide'),
  ('group_executive', 'core.pipeline_gate.read'),
  ('group_executive', 'core.pipeline_run.read'),
  ('group_executive', 'core.pipeline_stage.read'),
  ('group_executive', 'core.pipeline_stage.update'),
  ('group_executive', 'core.rollup.read'),
  ('group_executive', 'core.scope_signoff.create'),
  ('group_executive', 'core.scope_signoff.read'),
  ('group_executive', 'core.service_assignment.accept'),
  ('group_executive', 'core.service_assignment.propose'),
  ('group_executive', 'core.service_assignment.read'),
  ('group_executive', 'core.service_assignment.reconcile'),
  ('group_executive', 'core.service_assignment.relink'),
  ('group_executive', 'core.service_assignment.resume'),
  ('group_executive', 'core.service_assignment.revoke'),
  ('group_executive', 'core.service_assignment.suspend'),
  ('group_executive', 'core.work_activity.read'),
  ('group_executive', 'hr.case.cancel'),
  ('group_executive', 'hr.case.create'),
  ('group_executive', 'hr.case.delete'),
  ('group_executive', 'hr.case.export'),
  ('group_executive', 'hr.case.read'),
  ('group_executive', 'hr.case.update'),
  ('group_executive', 'it.device.create'),
  ('group_executive', 'it.device.delete'),
  ('group_executive', 'it.device.read'),
  ('group_executive', 'it.device.update'),
  ('group_executive', 'knowledge.source.read'),
  ('group_executive', 'knowledge.source.update'),
  ('group_executive', 'pm.project.manage'),
  ('group_executive', 'pm.project.read'),
  ('group_executive', 'pm.task.create'),
  ('group_executive', 'pm.task.delete'),
  ('group_executive', 'pm.task.manage'),
  ('group_executive', 'pm.task.read'),
  ('group_executive', 'pm.task.update'),
  ('group_executive', 'portal.read'),
  ('group_executive', 'reports.admin.recompute'),
  ('group_executive', 'reports.appraisal.read'),
  ('group_executive', 'reports.checkin.excuse'),
  ('group_executive', 'reports.checkin.read'),
  ('group_executive', 'reports.document.read_company'),
  ('group_executive', 'reports.document.read_department'),
  ('group_executive', 'reports.document.read_person'),
  ('group_executive', 'reports.document.read_project'),
  ('group_executive', 'reports.period.amend'),
  ('group_executive', 'reports.period.pin'),
  ('group_executive', 'reports.period.seal'),
  ('group_executive', 'reports.period.view'),
  ('group_executive', 'search.audit.create'),
  ('group_executive', 'search.audit.delete'),
  ('group_executive', 'search.audit.read'),
  ('group_executive', 'search.audit.run'),
  ('group_executive', 'search.audit.update'),
  ('group_executive', 'search.campaign.apply_manual'),
  ('group_executive', 'search.campaign.apply_negatives'),
  ('group_executive', 'search.campaign.create'),
  ('group_executive', 'search.campaign.delete'),
  ('group_executive', 'search.campaign.launch'),
  ('group_executive', 'search.campaign.propose_change'),
  ('group_executive', 'search.campaign.read'),
  ('group_executive', 'search.campaign.set_budget'),
  ('group_executive', 'search.campaign.update'),
  ('group_executive', 'search.engagement.create'),
  ('group_executive', 'search.engagement.delete'),
  ('group_executive', 'search.engagement.read'),
  ('group_executive', 'search.engagement.set_scope'),
  ('group_executive', 'search.engagement.update'),
  ('group_executive', 'search.keyword.create'),
  ('group_executive', 'search.keyword.delete'),
  ('group_executive', 'search.keyword.read'),
  ('group_executive', 'search.keyword.research'),
  ('group_executive', 'search.keyword.update'),
  ('group_executive', 'search.ledger.admin'),
  ('group_executive', 'search.ledger.read'),
  ('group_executive', 'search.property.create'),
  ('group_executive', 'search.property.delete'),
  ('group_executive', 'search.property.read'),
  ('group_executive', 'search.property.update'),
  ('group_executive', 'search.report.approve'),
  ('group_executive', 'search.report.create'),
  ('group_executive', 'search.report.delete'),
  ('group_executive', 'search.report.deliver'),
  ('group_executive', 'search.report.read'),
  ('group_executive', 'search.report.update'),
  ('group_executive', 'webdev.change_request.create'),
  ('group_executive', 'webdev.change_request.read'),
  ('group_executive', 'webdev.change_request.triage'),
  ('group_executive', 'webdev.provisioned_site.provision'),
  ('group_executive', 'webdev.provisioned_site.read'),
  ('group_executive', 'webdev.provisioned_site.reconcile'),
  ('manager', 'agency.approval.create'),
  ('manager', 'agency.approval.read'),
  ('manager', 'agency.brief.create'),
  ('manager', 'agency.brief.delete'),
  ('manager', 'agency.brief.read'),
  ('manager', 'agency.brief.update'),
  ('manager', 'agency.campaign.create'),
  ('manager', 'agency.campaign.delete'),
  ('manager', 'agency.campaign.read'),
  ('manager', 'agency.campaign.update'),
  ('manager', 'agency.creative_asset.create'),
  ('manager', 'agency.creative_asset.delete'),
  ('manager', 'agency.creative_asset.read'),
  ('manager', 'agency.creative_asset.update'),
  ('manager', 'billing.invoice.read'),
  ('manager', 'core.activity.read'),
  ('manager', 'core.automation_approval.create'),
  ('manager', 'core.automation_approval.read'),
  ('manager', 'core.client.create'),
  ('manager', 'core.client.delete'),
  ('manager', 'core.client.read'),
  ('manager', 'core.client.update'),
  ('manager', 'core.client_contact.create'),
  ('manager', 'core.client_contact.read'),
  ('manager', 'core.client_contact.revoke'),
  ('manager', 'core.client_contact.update'),
  ('manager', 'core.comment.create'),
  ('manager', 'core.comment.read'),
  ('manager', 'core.company.read'),
  ('manager', 'core.contract.read'),
  ('manager', 'core.custom_field.create'),
  ('manager', 'core.custom_field.delete'),
  ('manager', 'core.custom_field.read'),
  ('manager', 'core.custom_field.update'),
  ('manager', 'core.deliverable.create'),
  ('manager', 'core.deliverable.delete'),
  ('manager', 'core.deliverable.read'),
  ('manager', 'core.deliverable.update'),
  ('manager', 'core.file.create'),
  ('manager', 'core.file.delete'),
  ('manager', 'core.file.read'),
  ('manager', 'core.integration_connection.create'),
  ('manager', 'core.integration_connection.delete'),
  ('manager', 'core.integration_connection.read'),
  ('manager', 'core.integration_connection.update'),
  ('manager', 'core.meeting_recording.create'),
  ('manager', 'core.meeting_recording.ingest'),
  ('manager', 'core.meeting_recording.read'),
  ('manager', 'core.meeting_recording.sync_drive'),
  ('manager', 'core.meeting_recording.update'),
  ('manager', 'core.member.read'),
  ('manager', 'core.notification.create'),
  ('manager', 'core.notification.read'),
  ('manager', 'core.notification.update'),
  ('manager', 'core.org_structure.read'),
  ('manager', 'core.pipeline_gate.create'),
  ('manager', 'core.pipeline_gate.read'),
  ('manager', 'core.pipeline_run.create'),
  ('manager', 'core.pipeline_run.read'),
  ('manager', 'core.pipeline_run.update'),
  ('manager', 'core.pipeline_stage.create'),
  ('manager', 'core.pipeline_stage.read'),
  ('manager', 'core.pipeline_stage.update'),
  ('manager', 'core.project.create'),
  ('manager', 'core.project.delete'),
  ('manager', 'core.project.read'),
  ('manager', 'core.project.update'),
  ('manager', 'core.rollup_recompute.create'),
  ('manager', 'core.scope_signoff.create'),
  ('manager', 'core.scope_signoff.read'),
  ('manager', 'core.task.create'),
  ('manager', 'core.task.delete'),
  ('manager', 'core.task.read'),
  ('manager', 'core.task.update'),
  ('manager', 'core.team.create'),
  ('manager', 'core.team.delete'),
  ('manager', 'core.team.read'),
  ('manager', 'core.team.update'),
  ('manager', 'core.time_entry.create'),
  ('manager', 'core.time_entry.delete'),
  ('manager', 'core.time_entry.read'),
  ('manager', 'core.time_entry.update'),
  ('manager', 'core.user.read'),
  ('manager', 'core.work_activity.read'),
  ('manager', 'it.device.read'),
  ('manager', 'pm.project.manage'),
  ('manager', 'pm.project.read'),
  ('manager', 'pm.task.create'),
  ('manager', 'pm.task.delete'),
  ('manager', 'pm.task.manage'),
  ('manager', 'pm.task.read'),
  ('manager', 'pm.task.update'),
  ('manager', 'portal.read'),
  ('manager', 'reports.appraisal.confirm_evidence'),
  ('manager', 'reports.appraisal.read'),
  ('manager', 'reports.appraisal.submit'),
  ('manager', 'reports.appraisal.write'),
  ('manager', 'reports.checkin.excuse'),
  ('manager', 'reports.checkin.read'),
  ('manager', 'reports.document.read_department'),
  ('manager', 'reports.document.read_person'),
  ('manager', 'reports.document.read_project'),
  ('manager', 'reports.period.view'),
  ('manager', 'webdev.change_request.create'),
  ('manager', 'webdev.change_request.read'),
  ('manager', 'webdev.change_request.triage'),
  ('manager', 'webdev.provisioned_site.provision'),
  ('manager', 'webdev.provisioned_site.read'),
  ('manager', 'webdev.provisioned_site.reconcile'),
  ('member', 'agency.approval.create'),
  ('member', 'agency.approval.read'),
  ('member', 'agency.brief.create'),
  ('member', 'agency.brief.delete'),
  ('member', 'agency.brief.read'),
  ('member', 'agency.brief.update'),
  ('member', 'agency.campaign.read'),
  ('member', 'agency.creative_asset.create'),
  ('member', 'agency.creative_asset.delete'),
  ('member', 'agency.creative_asset.read'),
  ('member', 'agency.creative_asset.update'),
  ('member', 'core.activity.read'),
  ('member', 'core.automation_approval.create'),
  ('member', 'core.client.create'),
  ('member', 'core.client.delete'),
  ('member', 'core.client.read'),
  ('member', 'core.client.update'),
  ('member', 'core.client_contact.read'),
  ('member', 'core.comment.create'),
  ('member', 'core.comment.read'),
  ('member', 'core.company.read'),
  ('member', 'core.custom_field.read'),
  ('member', 'core.deliverable.create'),
  ('member', 'core.deliverable.delete'),
  ('member', 'core.deliverable.read'),
  ('member', 'core.deliverable.update'),
  ('member', 'core.file.create'),
  ('member', 'core.file.delete'),
  ('member', 'core.file.read'),
  ('member', 'core.integration_connection.create'),
  ('member', 'core.integration_connection.delete'),
  ('member', 'core.integration_connection.read'),
  ('member', 'core.integration_connection.update'),
  ('member', 'core.meeting_recording.create'),
  ('member', 'core.meeting_recording.ingest'),
  ('member', 'core.meeting_recording.read'),
  ('member', 'core.meeting_recording.sync_drive'),
  ('member', 'core.meeting_recording.update'),
  ('member', 'core.member.read'),
  ('member', 'core.notification.read'),
  ('member', 'core.notification.update'),
  ('member', 'core.org_structure.read'),
  ('member', 'core.pipeline_gate.create'),
  ('member', 'core.pipeline_run.create'),
  ('member', 'core.pipeline_run.update'),
  ('member', 'core.pipeline_stage.create'),
  ('member', 'core.project.create'),
  ('member', 'core.project.delete'),
  ('member', 'core.project.read'),
  ('member', 'core.project.update'),
  ('member', 'core.task.create'),
  ('member', 'core.task.delete'),
  ('member', 'core.task.read'),
  ('member', 'core.task.update'),
  ('member', 'core.team.read'),
  ('member', 'core.time_entry.create'),
  ('member', 'core.time_entry.delete'),
  ('member', 'core.time_entry.read'),
  ('member', 'core.time_entry.update'),
  ('member', 'core.work_activity.read'),
  ('member', 'hr.case.cancel'),
  ('member', 'hr.case.create'),
  ('member', 'hr.case.read'),
  ('member', 'it.device.read'),
  ('member', 'pm.project.read'),
  ('member', 'pm.task.read'),
  ('member', 'pm.task.update'),
  ('member', 'reports.appraisal.ack'),
  ('member', 'reports.appraisal.read'),
  ('member', 'reports.checkin.read'),
  ('member', 'reports.checkin.submit'),
  ('member', 'reports.document.read_person'),
  ('member', 'reports.document.read_project'),
  ('member', 'reports.period.view'),
  ('viewer', 'agency.approval.read'),
  ('viewer', 'agency.brief.read'),
  ('viewer', 'agency.campaign.read'),
  ('viewer', 'agency.creative_asset.read'),
  ('viewer', 'core.activity.read'),
  ('viewer', 'core.client.read'),
  ('viewer', 'core.client_contact.read'),
  ('viewer', 'core.comment.read'),
  ('viewer', 'core.company.read'),
  ('viewer', 'core.custom_field.read'),
  ('viewer', 'core.deliverable.read'),
  ('viewer', 'core.file.read'),
  ('viewer', 'core.integration_connection.create'),
  ('viewer', 'core.integration_connection.delete'),
  ('viewer', 'core.integration_connection.read'),
  ('viewer', 'core.integration_connection.update'),
  ('viewer', 'core.meeting_recording.read'),
  ('viewer', 'core.member.read'),
  ('viewer', 'core.notification.read'),
  ('viewer', 'core.notification.update'),
  ('viewer', 'core.org_structure.read'),
  ('viewer', 'core.project.read'),
  ('viewer', 'core.task.read'),
  ('viewer', 'core.team.read'),
  ('viewer', 'core.time_entry.read'),
  ('viewer', 'core.work_activity.read'),
  ('viewer', 'it.device.read'),
  ('viewer', 'pm.project.read'),
  ('viewer', 'pm.task.read'),
  ('viewer', 'pm.task.update'),
  ('team_lead', 'core.activity.read'),
  ('team_lead', 'core.client.create'),
  ('team_lead', 'core.client.delete'),
  ('team_lead', 'core.client.read'),
  ('team_lead', 'core.client.update'),
  ('team_lead', 'core.client_contact.read'),
  ('team_lead', 'core.comment.create'),
  ('team_lead', 'core.comment.read'),
  ('team_lead', 'core.custom_field.read'),
  ('team_lead', 'core.deliverable.create'),
  ('team_lead', 'core.deliverable.delete'),
  ('team_lead', 'core.deliverable.read'),
  ('team_lead', 'core.deliverable.update'),
  ('team_lead', 'core.file.create'),
  ('team_lead', 'core.file.delete'),
  ('team_lead', 'core.file.read'),
  ('team_lead', 'core.integration_connection.create'),
  ('team_lead', 'core.integration_connection.delete'),
  ('team_lead', 'core.integration_connection.read'),
  ('team_lead', 'core.integration_connection.update'),
  ('team_lead', 'core.meeting_recording.create'),
  ('team_lead', 'core.meeting_recording.ingest'),
  ('team_lead', 'core.meeting_recording.read'),
  ('team_lead', 'core.meeting_recording.sync_drive'),
  ('team_lead', 'core.meeting_recording.update'),
  ('team_lead', 'core.member.read'),
  ('team_lead', 'core.notification.read'),
  ('team_lead', 'core.notification.update'),
  ('team_lead', 'core.org_structure.read'),
  ('team_lead', 'core.project.create'),
  ('team_lead', 'core.project.delete'),
  ('team_lead', 'core.project.read'),
  ('team_lead', 'core.project.update'),
  ('team_lead', 'core.task.create'),
  ('team_lead', 'core.task.delete'),
  ('team_lead', 'core.task.read'),
  ('team_lead', 'core.task.update'),
  ('team_lead', 'core.team.read'),
  ('team_lead', 'core.team.update'),
  ('team_lead', 'core.time_entry.create'),
  ('team_lead', 'core.time_entry.delete'),
  ('team_lead', 'core.time_entry.read'),
  ('team_lead', 'core.time_entry.update'),
  ('team_lead', 'core.work_activity.read'),
  ('team_lead', 'it.device.read'),
  ('team_lead', 'pm.project.manage'),
  ('team_lead', 'pm.project.read'),
  ('team_lead', 'pm.task.create'),
  ('team_lead', 'pm.task.delete'),
  ('team_lead', 'pm.task.manage'),
  ('team_lead', 'pm.task.read'),
  ('team_lead', 'pm.task.update'),
  ('team_lead', 'reports.appraisal.confirm_evidence'),
  ('team_lead', 'reports.appraisal.read'),
  ('team_lead', 'reports.appraisal.submit'),
  ('team_lead', 'reports.appraisal.write'),
  ('team_lead', 'reports.document.read_department'),
  ('team_lead', 'reports.document.read_person'),
  ('team_lead', 'reports.document.read_project'),
  ('team_lead', 'reports.period.view'),
  ('client', 'portal.decide'),
  ('client', 'portal.pay'),
  ('client', 'portal.read'),
  ('client', 'portal.request_change'),
  ('client', 'portal.sign'),
  ('client', 'portal.update_profile'),
  ('it_admin', 'it.device.create'),
  ('it_admin', 'it.device.delete'),
  ('it_admin', 'it.device.update'),
  ('it_manager', 'it.device.create'),
  ('it_manager', 'it.device.delete'),
  ('it_manager', 'it.device.update'),
  ('it', 'it.device.create'),
  ('it', 'it.device.delete'),
  ('it', 'it.device.update'),
  ('agency_approver', 'agency.approval.approve'),
  ('hr_staff', 'core.member.read'),
  ('hr_staff', 'core.service_assignment.read'),
  ('hr_staff', 'hr.case.create'),
  ('hr_staff', 'hr.case.read'),
  ('hr_staff', 'hr.case.update'),
  ('hr_staff', 'hr.record.create'),
  ('hr_staff', 'hr.record.read'),
  ('hr_staff', 'hr.record.update'),
  ('hr_staff', 'reports.checkin.read'),
  ('hr_staff', 'reports.document.read_department'),
  ('hr_staff', 'reports.document.read_person'),
  ('hr_staff', 'reports.document.read_project'),
  ('hr_staff', 'reports.period.view'),
  ('hr_manager', 'core.automation_approval.decide'),
  ('hr_manager', 'core.automation_approval.read'),
  ('hr_manager', 'core.service_assignment.read'),
  ('hr_manager', 'hr.case.create'),
  ('hr_manager', 'hr.case.delete'),
  ('hr_manager', 'hr.case.export'),
  ('hr_manager', 'hr.case.read'),
  ('hr_manager', 'hr.case.update'),
  ('hr_manager', 'hr.record.create'),
  ('hr_manager', 'hr.record.delete'),
  ('hr_manager', 'hr.record.export'),
  ('hr_manager', 'hr.record.read'),
  ('hr_manager', 'hr.record.update'),
  ('hr_manager', 'reports.appraisal.confirm_evidence'),
  ('hr_manager', 'reports.appraisal.cycle_admin'),
  ('hr_manager', 'reports.appraisal.finalize'),
  ('hr_manager', 'reports.appraisal.read'),
  ('hr_manager', 'reports.checkin.excuse'),
  ('hr_manager', 'reports.checkin.read'),
  ('hr_manager', 'reports.document.read_department'),
  ('hr_manager', 'reports.document.read_person'),
  ('hr_manager', 'reports.document.read_project'),
  ('hr_manager', 'reports.period.view'),
  ('search_staff', 'core.member.read'),
  ('search_staff', 'core.service_assignment.read'),
  ('search_staff', 'search.audit.create'),
  ('search_staff', 'search.audit.read'),
  ('search_staff', 'search.audit.run'),
  ('search_staff', 'search.audit.update'),
  ('search_staff', 'search.campaign.create'),
  ('search_staff', 'search.campaign.propose_change'),
  ('search_staff', 'search.campaign.read'),
  ('search_staff', 'search.campaign.update'),
  ('search_staff', 'search.engagement.create'),
  ('search_staff', 'search.engagement.read'),
  ('search_staff', 'search.engagement.update'),
  ('search_staff', 'search.keyword.create'),
  ('search_staff', 'search.keyword.read'),
  ('search_staff', 'search.keyword.research'),
  ('search_staff', 'search.keyword.update'),
  ('search_staff', 'search.ledger.read'),
  ('search_staff', 'search.property.create'),
  ('search_staff', 'search.property.read'),
  ('search_staff', 'search.property.update'),
  ('search_staff', 'search.report.create'),
  ('search_staff', 'search.report.read'),
  ('search_staff', 'search.report.update'),
  ('search_manager', 'core.service_assignment.read'),
  ('search_manager', 'search.audit.create'),
  ('search_manager', 'search.audit.delete'),
  ('search_manager', 'search.audit.read'),
  ('search_manager', 'search.audit.run'),
  ('search_manager', 'search.audit.update'),
  ('search_manager', 'search.campaign.apply_manual'),
  ('search_manager', 'search.campaign.apply_negatives'),
  ('search_manager', 'search.campaign.create'),
  ('search_manager', 'search.campaign.delete'),
  ('search_manager', 'search.campaign.launch'),
  ('search_manager', 'search.campaign.propose_change'),
  ('search_manager', 'search.campaign.read'),
  ('search_manager', 'search.campaign.set_budget'),
  ('search_manager', 'search.campaign.update'),
  ('search_manager', 'search.engagement.create'),
  ('search_manager', 'search.engagement.delete'),
  ('search_manager', 'search.engagement.read'),
  ('search_manager', 'search.engagement.set_scope'),
  ('search_manager', 'search.engagement.update'),
  ('search_manager', 'search.keyword.create'),
  ('search_manager', 'search.keyword.delete'),
  ('search_manager', 'search.keyword.read'),
  ('search_manager', 'search.keyword.research'),
  ('search_manager', 'search.keyword.update'),
  ('search_manager', 'search.ledger.admin'),
  ('search_manager', 'search.ledger.read'),
  ('search_manager', 'search.property.create'),
  ('search_manager', 'search.property.delete'),
  ('search_manager', 'search.property.read'),
  ('search_manager', 'search.property.update'),
  ('search_manager', 'search.report.approve'),
  ('search_manager', 'search.report.create'),
  ('search_manager', 'search.report.delete'),
  ('search_manager', 'search.report.deliver'),
  ('search_manager', 'search.report.read'),
  ('search_manager', 'search.report.update'),
  ('reports_staff', 'core.member.read'),
  ('reports_staff', 'core.service_assignment.read'),
  ('reports_staff', 'reports.document.read_department'),
  ('reports_staff', 'reports.document.read_project'),
  ('reports_manager', 'core.service_assignment.read'),
  ('reports_manager', 'reports.document.read_department'),
  ('reports_manager', 'reports.document.read_project')
) AS bundle(role_name, perm_key)
JOIN roles r ON r.company_id IS NULL AND r.name = bundle.role_name
JOIN permissions p ON p.key = bundle.perm_key
ON CONFLICT DO NOTHING;

-- ── Assert, don't assume ──────────────────────────────────────────────────────────────────────────
-- Per-role exact-count check catches both (a) a typo'd role name or permission key that silently
-- dropped a row from the JOIN, and (b) a double-count from an unexpectedly-duplicated global role
-- row. Total-count check is redundant with the sum of the per-role checks but kept as a cheap
-- top-level tripwire, matching 0093/0095's own "assert the exact post-seed shape" idiom.
DO $$
DECLARE
  expected record;
  got integer;
  total_expected integer := 925;
  total_got integer;
  leaked integer;
BEGIN
  FOR expected IN
    SELECT * FROM (VALUES
      ('platform_admin', 215),
      ('company_admin', 199),
      ('group_executive', 118),
      ('manager', 109),
      ('member', 74),
      ('viewer', 30),
      ('team_lead', 60),
      ('client', 6),
      ('it_admin', 3),
      ('it_manager', 3),
      ('it', 3),
      ('agency_approver', 1),
      ('hr_staff', 13),
      ('hr_manager', 23),
      ('search_staff', 24),
      ('search_manager', 37),
      ('reports_staff', 4),
      ('reports_manager', 3)
    ) AS x(role_name, expected_count)
  LOOP
    SELECT count(*) INTO got
      FROM role_permissions rp
      JOIN roles r ON r.id = rp.role_id
     WHERE r.company_id IS NULL AND r.name = expected.role_name;
    IF got <> expected.expected_count THEN
      RAISE EXCEPTION '0094: role "%": expected % bundled permissions, found %',
        expected.role_name, expected.expected_count, got;
    END IF;
  END LOOP;

  SELECT count(*) INTO total_got
    FROM role_permissions rp
    JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL
     AND r.name IN ('platform_admin','company_admin','group_executive','manager','member','viewer',
                    'team_lead','client','it_admin','it_manager','it','agency_approver',
                    'hr_staff','hr_manager','search_staff','search_manager',
                    'reports_staff','reports_manager');
  IF total_got <> total_expected THEN
    RAISE EXCEPTION '0094: total bundled permissions across the 18 built-in roles: expected %, found %',
      total_expected, total_got;
  END IF;

  -- Defense-in-depth re-assertion of Ruling 3, redundant with 0093's DB trigger: no bundle may ever
  -- contain a class='relationship' permission.
  SELECT count(*) INTO leaked
    FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
   WHERE p.class = 'relationship';
  IF leaked <> 0 THEN
    RAISE EXCEPTION '0094: % relationship-class permission(s) leaked into role_permissions — Ruling 3 violated', leaked;
  END IF;

  RAISE NOTICE '0094: role_permissions seeded — % rows across 18 built-in roles, 0 relationship-class leaks', total_got;
END $$;
