-- 0114_iam_self_scoped_marker.sql — the per-(role, permission) SELF-SCOPED marker that replaces
-- P2-08's interim "subtract the baseline `member` bundle" inside the grant ceiling.
--
-- Owner ruling 2026-08-18 (docs/PERMISSION-CONTRACT.md §12.1): the durable form of the ceiling's
-- exclusion is a marker distinguishing SELF-SCOPED keys (authority over the holder's own rows) from
-- authority-over-others keys — not a subtraction of one role's whole bundle.
--
-- ── WHY A SUBTRACTION WAS NOT GOOD ENOUGH (the worked example, both from `member`'s bundle) ─────
--   * `hr.case.cancel`     — self-scoped: cancel MY OWN case. Confers nothing over anybody else.
--   * `core.client.delete` — NOT self-scoped. It was real tenant-wide reach, and it was a LIVE
--                            over-grant until 2026-08-18 (§12.5).
-- Subtracting `bundle(member)` removed both. This marker removes only the first.
--
-- ── DERIVED, NOT HAND-LISTED ───────────────────────────────────────────────────────────────────
-- The 21 pairs below are generated by `scripts/generate-role-bundles.mjs::computeSelfScoped`, whose
-- predicate is copied verbatim from `permission-arm-hazard-scan.test.ts::selfScopeField` (its
-- "Pattern B" check). A pair is marked when EVERY ALLOW rule granting that key to that role carries a
-- self-scope condition (`request.resource.attr.X == request.principal.id`, or `variables.owns`) and
-- NO unconditional/scope-only rule also grants it. `role-permission-bundles.json` carries the same
-- list under `selfScoped`, and `self-scoped-marker-parity.db.test.ts` fails if the two disagree — so
-- a policy edit that changes this set shows up as a red test, not as silent drift.
--
-- ── WHAT THIS MIGRATION DOES NOT DO ────────────────────────────────────────────────────────────
-- It does NOT remove the baseline consideration from the ceiling. Measured before writing this:
-- with the marker alone, `org_unit_lead` granting `member` is short 55 keys and `hr_manager`
-- granting `hr_staff` is short one (`core.member.read`) — i.e. marker-only re-breaks the dept-head
-- surface. The baseline now lives on the HELD side of the comparison instead
-- (`grant-write.service.ts::assertWithinCeiling`), which is where it reads truthfully: a grantor is
-- themselves staff, so passing on baseline reach confers nothing new.
--
-- ── NUMBERING ──────────────────────────────────────────────────────────────────────────────────
-- `ls migrations | sort | tail` immediately before writing showed the head as
-- `0113_social_inbox_retention.sql` (a concurrent session took 0113), so this is `0114`.
-- `0058`/`0059`/`0070` remain the permanently-orphaned reservation gaps — not touched.

ALTER TABLE role_permissions
  ADD COLUMN IF NOT EXISTS self_scoped boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN role_permissions.self_scoped IS
  'IAM (owner ruling 2026-08-18): TRUE when every Cerbos ALLOW rule granting this permission to this '
  'role is self-scoped (resource.attr.X == principal.id, or variables.owns) — i.e. it confers authority '
  'over the holder''s OWN rows only. The grant ceiling excludes these from the set a grantor must hold. '
  'Generated by scripts/generate-role-bundles.mjs; parity-tested against role-permission-bundles.json.';

DO $$
DECLARE
  marked integer;
  expected integer := 21;
BEGIN
  -- Idempotent: recompute from scratch so a re-run (or a later migration that re-seeds bundles)
  -- cannot leave a stale TRUE behind on a pair that stopped being self-scoped.
  UPDATE role_permissions SET self_scoped = false WHERE self_scoped;

  WITH wanted(role_name, perm_key) AS (VALUES
    ('member', 'core.integration_connection.create'),
    ('member', 'core.integration_connection.delete'),
    ('member', 'core.integration_connection.read'),
    ('member', 'core.integration_connection.update'),
    ('member', 'core.project.create'),
    ('member', 'core.project.delete'),
    ('member', 'core.project.update'),
    ('member', 'core.time_entry.delete'),
    ('member', 'core.time_entry.update'),
    ('member', 'hr.case.cancel'),
    ('member', 'hr.case.create'),
    ('member', 'hr.case.read'),
    ('member', 'reports.appraisal.ack'),
    ('member', 'reports.appraisal.read'),
    ('member', 'reports.checkin.read'),
    ('member', 'reports.checkin.submit'),
    ('member', 'reports.document.read_person'),
    ('viewer', 'core.integration_connection.create'),
    ('viewer', 'core.integration_connection.delete'),
    ('viewer', 'core.integration_connection.read'),
    ('viewer', 'core.integration_connection.update')
  )
  UPDATE role_permissions rp
     SET self_scoped = true
    FROM wanted w
    JOIN roles r ON r.name = w.role_name AND r.company_id IS NULL
    JOIN permissions p ON p.key = w.perm_key
   WHERE rp.role_id = r.id AND rp.permission_id = p.id;
  GET DIAGNOSTICS marked = ROW_COUNT;

  -- A DELTA assertion, not a claim about the table forever (the 0093 lesson). If a pair in the list
  -- has no bundle row, the generator and the seeded bundles disagree and that must stop the deploy —
  -- a silently-unmarked pair means the ceiling demands a self-service key the grantor cannot hold.
  IF marked <> expected THEN
    RAISE EXCEPTION
      'self_scoped: expected to mark % (role, permission) pairs, marked % — the generated list and '
      'the seeded bundles disagree. Re-run `npm run gen:role-bundles` and reconcile before deploying.',
      expected, marked;
  END IF;
END $$;
