-- LMS L1 — the IAM half: two new roles, twelve permissions, and their bundles.
--
-- GENERATED by scripts/build-lms-l1-iam-migration.mjs from src/rbac/permission-catalog.json and
-- src/rbac/role-permission-bundles.json. Frozen once applied.
--
-- Schema for the module itself is 202608241322_module_lms_l1.sql. Design:
-- docs/blueprints/lms-foundation.md.
--
-- ══ 1 · WHY TWO NEW ROLES, AND WHY THEY MUST BE SEEDED ═════════════════════════════════════════
-- `lms_staff` and `lms_manager`. Every other module in the estate has this pair (hr, monitoring,
-- reports, search, social, webdev — verified against the live `roles` table 2026-08-24), and
-- `service-reconciler.ts::moduleRoleId` materializes `${moduleKey}_${kind}` GENERICALLY — but it
-- returns NULL if the role is unseeded, and then silently materializes nothing.
--
-- So referencing `module_staff` on an lms kind WITHOUT seeding these two would produce exactly the
-- defect derived_roles.yaml warns about by name: "an unreachable tier written into a contract" — a
-- policy nobody can ever satisfy, failing silently rather than loudly. Seeding them is two rows and
-- it makes LMS a first-class module like the other six, including the shared-service path if a
-- group training function ever serves LMS to another company.
--
-- ══ 2 · THE TWO KINDS ══════════════════════════════════════════════════════════════════════════
--   lms_course      the authored catalogue. READ IS DELIBERATELY WIDE (every member) — training you
--                   cannot see is a support ticket, the same reasoning resource_hr_policy.yaml
--                   records for holiday calendars. Authoring is scoped to the DEPARTMENT HEAD via
--                   `org_unit_lead`'s existing unitAncestors containment; no new role was needed
--                   for the owner's "each HOD makes more" requirement.
--   lms_enrollment  the OPPOSITE posture: a learner's progress, scores and FAILED attempts are
--                   personal data about a named person. Three tiers — the learner over their own,
--                   the department head over their unit, HR/admin company-wide for compliance.
--
-- Two actions are deliberately NOT folded into `update`, and both would be real defects if they
-- were: `grade` (else a learner grades themselves) and `waive` (excusing somebody from mandatory
-- training is a compliance decision, not an assessment — and a department head must not be able to
-- excuse their whole team from the company's mandatory track).
--
-- ══ 3 · ROLE-ARM ONLY. No perm_* mirror, for either kind. ══════════════════════════════════════
-- Same posture as HR-FULL's three kinds and resource_employee.yaml (P2-02), and here it is
-- load-bearing: every non-admin rule is ATTRIBUTE-GATED — `subjectUserId` self on lms_enrollment,
-- `unitAncestors` containment on both. A flat permission mirror can express neither, and would
-- collapse "your own progress" into "everybody's progress" and "your own department's curriculum"
-- into "every department's". That is the granularity gap resource_hr_case.yaml documents at length.
--
-- ══ 4 · `owner` must be mirrored explicitly ════════════════════════════════════════════════════
-- 202608221409_iam14_owner_role.sql seeded `owner` as a ONE-TIME snapshot of company_admin's rows;
-- later keys do NOT propagate, and owner-role.db.test.ts asserts the two match EXACTLY. None of
-- these twelve falls on that migration's documented exclusions.
--
-- ⚠ CERBOS DOES NOT HOT-RELOAD. Two new resource_*.yaml files; restart it and PROVE a decision with
--   a probe. A healthy container has served stale policy in this estate before.

-- ══════════════════════════════════════════════════════════════════════════════════════════════
-- 1 · The two module roles. ON CONFLICT DO NOTHING so a re-run is inert.
-- ══════════════════════════════════════════════════════════════════════════════════════════════
INSERT INTO roles (id, company_id, name, description)
SELECT gen_random_uuid(), NULL, v.name, v.description
FROM (VALUES
  ('lms_staff',
   'LMS staff — reads the catalogue and the training register for a company. The baseline tier, '
   'mirroring hr_staff/search_staff. Materialized by service-reconciler.ts for a served company.'),
  ('lms_manager',
   'LMS manager — the ACTING tier: authors, publishes and retires courses, assigns paths, grades '
   'reviewed submissions. Mirrors hr_manager/search_manager.')
) AS v(name, description)
WHERE NOT EXISTS (SELECT 1 FROM roles r WHERE r.company_id IS NULL AND r.name = v.name);

-- ══════════════════════════════════════════════════════════════════════════════════════════════
-- 2 · Catalog permissions. ON CONFLICT (key) DO UPDATE so a re-run syncs metadata without churning
--     the id that role_permissions rows reference (0117's idiom).
-- ══════════════════════════════════════════════════════════════════════════════════════════════
INSERT INTO permissions (id, key, module_key, resource, action, description, cerbos_kind, cerbos_action, class, sensitive, ui_grantable)
SELECT gen_random_uuid(), v.key, v.module_key, v.resource, v.action, v.description, v.cerbos_kind, v.cerbos_action, v.class, v.sensitive, v.ui_grantable
FROM (VALUES
  ('lms.course.create', 'lms', 'course', 'create',
   'Author a course or path. Scoped to your own department for a department '
   'head; company-wide for an admin.',
   'lms_course', 'create', 'grantable', false, true),
  ('lms.course.delete', 'lms', 'course', 'delete',
   'Delete a course. Admin only — a course with completions against it should be '
   'retired, not deleted.',
   'lms_course', 'delete', 'grantable', true, true),
  ('lms.course.publish', 'lms', 'course', 'publish',
   'Publish a course version, making it assignable and freezing what learners '
   'will be certified against.',
   'lms_course', 'publish', 'grantable', true, true),
  ('lms.course.read', 'lms', 'course', 'read',
   'Browse the learning catalogue — courses, modules, activities and paths. '
   'Deliberately wide: training you cannot see is a support ticket.',
   'lms_course', 'read', 'grantable', false, true),
  ('lms.course.retire', 'lms', 'course', 'retire',
   'Withdraw a course from assignment. Existing completions keep referencing the '
   'retired version.',
   'lms_course', 'retire', 'grantable', false, true),
  ('lms.course.update', 'lms', 'course', 'update',
   'Edit a course or path. Editing a PUBLISHED course opens a new version rather '
   'than mutating the one learners are on.',
   'lms_course', 'update', 'grantable', false, true),
  ('lms.enrollment.create', 'lms', 'enrollment', 'create',
   'Assign a learning path to someone (or enrol yourself in an optional one).',
   'lms_enrollment', 'create', 'grantable', true, true),
  ('lms.enrollment.export', 'lms', 'enrollment', 'export',
   'Bulk-export the training register. Personal data about every employee at '
   'once; high assurance only.',
   'lms_enrollment', 'export', 'grantable', true, true),
  ('lms.enrollment.grade', 'lms', 'enrollment', 'grade',
   'Grade a submitted attempt for a reviewed activity (UI/UX, management '
   'scenarios). Separate from update so a learner can never grade themselves.',
   'lms_enrollment', 'grade', 'grantable', true, true),
  ('lms.enrollment.read', 'lms', 'enrollment', 'read',
   'Read enrolments, progress and scores. A learner reads their own; a '
   'department head their unit''s; HR company-wide.',
   'lms_enrollment', 'read', 'grantable', true, true),
  ('lms.enrollment.update', 'lms', 'enrollment', 'update',
   'Record progress and submit attempts. A learner updates their own.',
   'lms_enrollment', 'update', 'grantable', true, true),
  ('lms.enrollment.waive', 'lms', 'enrollment', 'waive',
   'Excuse somebody from mandatory training. A compliance decision, not an '
   'assessment — admin tier only.',
   'lms_enrollment', 'waive', 'grantable', true, true)
) AS v(key, module_key, resource, action, description, cerbos_kind, cerbos_action, class, sensitive, ui_grantable)
ON CONFLICT (key) DO UPDATE SET
  module_key = EXCLUDED.module_key, resource = EXCLUDED.resource, action = EXCLUDED.action,
  description = EXCLUDED.description, cerbos_kind = EXCLUDED.cerbos_kind,
  cerbos_action = EXCLUDED.cerbos_action, class = EXCLUDED.class,
  sensitive = EXCLUDED.sensitive, ui_grantable = EXCLUDED.ui_grantable;

-- ══════════════════════════════════════════════════════════════════════════════════════════════
-- 3 · Role bundles, carrying the 0114 self-scoped marker per row.
-- ══════════════════════════════════════════════════════════════════════════════════════════════
INSERT INTO role_permissions (role_id, permission_id, self_scoped)
SELECT r.id, p.id, bundle.self_scoped
FROM (VALUES
  ('member', 'lms.course.read', false),
  ('member', 'lms.enrollment.create', true),
  ('member', 'lms.enrollment.read', true),
  ('member', 'lms.enrollment.update', true),
  ('lms_staff', 'lms.course.read', false),
  ('lms_staff', 'lms.enrollment.read', false),
  ('lms_manager', 'lms.course.create', false),
  ('lms_manager', 'lms.course.publish', false),
  ('lms_manager', 'lms.course.read', false),
  ('lms_manager', 'lms.course.retire', false),
  ('lms_manager', 'lms.course.update', false),
  ('lms_manager', 'lms.enrollment.create', false),
  ('lms_manager', 'lms.enrollment.export', false),
  ('lms_manager', 'lms.enrollment.grade', false),
  ('lms_manager', 'lms.enrollment.read', false),
  ('lms_manager', 'lms.enrollment.update', false),
  ('lms_manager', 'lms.enrollment.waive', false),
  ('org_unit_lead', 'lms.course.create', false),
  ('org_unit_lead', 'lms.course.publish', false),
  ('org_unit_lead', 'lms.course.retire', false),
  ('org_unit_lead', 'lms.course.update', false),
  ('org_unit_lead', 'lms.enrollment.create', false),
  ('org_unit_lead', 'lms.enrollment.grade', false),
  ('org_unit_lead', 'lms.enrollment.read', false),
  ('org_unit_lead', 'lms.enrollment.update', false),
  ('hr_staff', 'lms.enrollment.read', false),
  ('hr_manager', 'lms.enrollment.create', false),
  ('hr_manager', 'lms.enrollment.export', false),
  ('hr_manager', 'lms.enrollment.grade', false),
  ('hr_manager', 'lms.enrollment.read', false),
  ('hr_manager', 'lms.enrollment.update', false),
  ('hr_manager', 'lms.enrollment.waive', false),
  ('company_admin', 'lms.course.create', false),
  ('company_admin', 'lms.course.delete', false),
  ('company_admin', 'lms.course.publish', false),
  ('company_admin', 'lms.course.read', false),
  ('company_admin', 'lms.course.retire', false),
  ('company_admin', 'lms.course.update', false),
  ('company_admin', 'lms.enrollment.create', false),
  ('company_admin', 'lms.enrollment.export', false),
  ('company_admin', 'lms.enrollment.grade', false),
  ('company_admin', 'lms.enrollment.read', false),
  ('company_admin', 'lms.enrollment.update', false),
  ('company_admin', 'lms.enrollment.waive', false),
  ('platform_admin', 'lms.course.create', false),
  ('platform_admin', 'lms.course.delete', false),
  ('platform_admin', 'lms.course.publish', false),
  ('platform_admin', 'lms.course.read', false),
  ('platform_admin', 'lms.course.retire', false),
  ('platform_admin', 'lms.course.update', false),
  ('platform_admin', 'lms.enrollment.create', false),
  ('platform_admin', 'lms.enrollment.export', false),
  ('platform_admin', 'lms.enrollment.grade', false),
  ('platform_admin', 'lms.enrollment.read', false),
  ('platform_admin', 'lms.enrollment.update', false),
  ('platform_admin', 'lms.enrollment.waive', false),
  ('owner', 'lms.course.create', false),
  ('owner', 'lms.course.delete', false),
  ('owner', 'lms.course.publish', false),
  ('owner', 'lms.course.read', false),
  ('owner', 'lms.course.retire', false),
  ('owner', 'lms.course.update', false),
  ('owner', 'lms.enrollment.create', false),
  ('owner', 'lms.enrollment.export', false),
  ('owner', 'lms.enrollment.grade', false),
  ('owner', 'lms.enrollment.read', false),
  ('owner', 'lms.enrollment.update', false),
  ('owner', 'lms.enrollment.waive', false)
) AS bundle(role_name, perm_key, self_scoped)
JOIN roles r ON r.company_id IS NULL AND r.name = bundle.role_name
JOIN permissions p ON p.key = bundle.perm_key
ON CONFLICT (role_id, permission_id) DO UPDATE SET self_scoped = EXCLUDED.self_scoped;

-- ══════════════════════════════════════════════════════════════════════════════════════════════
-- 4 · Self-check. Floors where later growth is legitimate; equalities only where the header argues
--     for one.
-- ══════════════════════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  n_roles  integer;
  n_perm   integer;
  n_bundle integer;
  n_owner  integer;
  n_ca     integer;
  n_waive  integer;
BEGIN
  SELECT count(*) INTO n_roles FROM roles WHERE company_id IS NULL AND name IN ('lms_staff','lms_manager');
  IF n_roles <> 2 THEN
    RAISE EXCEPTION 'LMS-L1: expected lms_staff + lms_manager to exist, found %', n_roles;
  END IF;

  SELECT count(*) INTO n_perm FROM permissions WHERE key LIKE 'lms.%';
  IF n_perm <> 12 THEN
    RAISE EXCEPTION 'LMS-L1: expected 12 lms permissions, found %', n_perm;
  END IF;

  SELECT count(*) INTO n_bundle FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id WHERE p.key LIKE 'lms.%';
  IF n_bundle < 68 THEN
    RAISE EXCEPTION 'LMS-L1: expected at least 68 bundle rows, found %', n_bundle;
  END IF;

  SELECT count(*) INTO n_owner FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'owner' AND p.key LIKE 'lms.%';
  SELECT count(*) INTO n_ca FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'company_admin' AND p.key LIKE 'lms.%';
  IF n_owner <> n_ca THEN
    RAISE EXCEPTION 'LMS-L1: owner holds % lms keys, company_admin holds % — must match (owner-role.db.test.ts)', n_owner, n_ca;
  END IF;

  -- The header's argument, asserted: a DEPARTMENT HEAD must not be able to excuse their own team
  -- from the company's mandatory training. If a future change gives org_unit_lead this key, this
  -- is the line that should be revisited deliberately rather than discovered.
  SELECT count(*) INTO n_waive FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'org_unit_lead' AND p.key = 'lms.enrollment.waive';
  IF n_waive <> 0 THEN
    RAISE EXCEPTION 'LMS-L1: org_unit_lead must NOT hold lms.enrollment.waive, found % row(s)', n_waive;
  END IF;
END $$;
