-- HR-FULL — the IAM half of the HR department build (waves A–D, 2026-08-24).
--
-- GENERATED by scripts/build-hr-full-iam-migration.mjs from src/rbac/permission-catalog.json and
-- src/rbac/role-permission-bundles.json. Frozen once applied; a later catalog change is a NEW
-- migration, never a re-run of this file.
--
-- Lands the 18 new grantable permissions across the THREE new Cerbos kinds this change introduces
-- (`hr_policy`, `hr_recruitment`, `hr_payroll`) and bundles them onto the role-arm roles those
-- policies actually name. No schema here; the tables live in 202608240140–0143.
--
-- ── The three kinds, and why they are three ─────────────────────────────────────────────────────
--   hr_policy       the company's own RULES (holiday calendars, leave policies, review cycles,
--                   pay-grade structure, statutory parameter sets). Read is DELIBERATELY WIDE —
--                   there is no person on the other side of a holiday calendar, and hiding the
--                   leave policy from the people it governs is a support ticket, not a posture.
--   hr_recruitment  the ATS. WIDER than hr_case on read (the interview panel is ordinary staff from
--                   the delivering department) and NARROWER on write (candidate data is outsider PD
--                   under consent, and hr_case's `member` self-service rule is meaningless for a
--                   subject who is not a platform principal at all).
--   hr_payroll      the MONEY tier. A deliberate step ABOVE hr_record: an HR assistant who
--                   legitimately files leave and uploads contracts has no business reading the
--                   company's salary book, and folding payroll into hr_record would have granted
--                   exactly that to every existing hr_staff holder the moment the tables landed.
--
-- ── ROLE-ARM ONLY. No perm_* derived-role mirror, for any of the three. ─────────────────────────
-- Same posture resource_employee.yaml took under P2-02 ("new kinds get an arm only after their
-- handlers exist and their holders are audited"), and here it is load-bearing rather than merely
-- cautious. role-permission-bundles.json's generator treats a resource-instance CONDITION as
-- satisfied when computing reach, so `member` shows up holding `hr.payroll.read` and
-- `hr.recruitment.read/create/update` purely because the policies carry self-scoped and
-- panel-scoped rules for those actions. `attr.perms` carries no record of WHICH rule a key came
-- through, so a permission-arm rule testing "does perms contain hr.payroll.read" could not tell
-- "your own published payslip" from "the whole company's salary book". This is the same granularity
-- gap resource_hr_case.yaml documents at length for hr.case.read; the mitigation there was to omit
-- the mirror, and it is omitted here for all three kinds.
--
-- ── `member` IS seeded, and that is the ESTABLISHED precedent, not a new concession ────────────
-- `member` shows up holding hr.payroll.read and hr.recruitment.read/create/update. Excluding those
-- rows was tried while writing this migration and is wrong for two reasons:
--
--   1. It breaks a live invariant. `role-permission-parity.db.test.ts` compares the seeded
--      `role_permissions` table against what Cerbos ACTUALLY grants, and Cerbos does grant `member`
--      these actions — through the self-scoped payslip rule and the panel rules. A bundle row that
--      is absent while the policy grants the action is a genuine disagreement between the two, and
--      the test is right to fail on it.
--   2. 0094 already did exactly this for `hr_case`. `member` carries hr.case.read/create/cancel
--      from that kind's own self-only rule, on the identical reasoning. Treating the new kinds
--      differently would leave one odd case out with no principle behind it.
--
-- THE SAFETY ARGUMENT IS THE ABSENT MIRROR, NOT AN ABSENT ROW. A bundle row is only dangerous if
-- some rule can be reached by holding the key alone — which is precisely what a perm_* derived role
-- would allow, and precisely why none is wired here. If anyone later adds one, THIS is the block to
-- re-read: the fix then is a self-scoped mirror carrying the same condition (resource_hr_case.yaml's
-- perm_hr_case_read_self is the worked shape), never an unconditional one.
--
-- ── The 0114 SELF-SCOPED marker ────────────────────────────────────────────────────────────────
-- Section 2 carries `self_scoped` per row, taken from the generator's own `selfScoped` map. All
-- four of `member`'s narrow keys are marked: `hr.payroll.read` (a `subjectUserId == principal.id`
-- self-check) and the three `hr_recruitment` keys (MEMBERSHIP in the attached-users list — "you
-- are on this interview panel").
--
-- WARNING — the membership form only classifies correctly because TWO things were changed for it,
--   and an edit undoing either one silently re-breaks this:
--
--     1. `isSelfScopedCondition` (scripts/generate-role-bundles.mjs) and its twin `selfScopeField`
--        (permission-arm-hazard-scan.test.ts) learned `principal.id in resource.attr.X`. Before
--        that they recognized only `attr.X == principal.id` and `variables.owns`.
--     2. resource_hr_recruitment.yaml INLINES its panel conditions rather than factoring them into
--        `variables.local`. Both predicates match on the RULE'S CONDITION TEXT, so a bare
--        `variables.isPanelist` reference is opaque to them.
--
--   Why it matters, concretely: an unmarked key counts as tenant-wide HR authority in `routeFor()`
--   (src/admin/role-grants.controller.ts), which routed an IAM override request for a NON-HR role
--   to hr_manager instead of company_admin. Caught by override-request-decide.test.ts's "a non-hr
--   role routes to company_admin" — NOT by any HR test, which is why the FULL suite was the gate
--   that mattered here.
--
-- ── `owner` must be mirrored explicitly ─────────────────────────────────────────────────────────
-- 202608221409_iam14_owner_role.sql seeded `owner` as a ONE-TIME snapshot of company_admin's rows.
-- Keys added to company_admin later do NOT propagate, and owner-role.db.test.ts asserts the two
-- bundles match EXACTLY — so every migration landing new company_admin keys must mirror them or
-- that suite goes red. None of these 18 falls on that migration's 19 documented exclusions: they
-- are not portal.*, not a platform credential, not a cross-company operator surface.
--
-- ⚠ CERBOS DOES NOT HOT-RELOAD. The three new resource_*.yaml files need a Cerbos restart, and a
--   HEALTHY Cerbos container has served two-day-stale policy in this program before. Restart it,
--   then PROVE a new decision with a probe — health is not currency.

-- ══════════════════════════════════════════════════════════════════════════════════════════════════
-- 1 · Catalog permissions. ON CONFLICT (key) DO UPDATE so a re-run is a metadata sync and never
--     churns the id that role_permissions rows reference (0117's idiom).
-- ══════════════════════════════════════════════════════════════════════════════════════════════════
INSERT INTO permissions (id, key, module_key, resource, action, description, cerbos_kind, cerbos_action, class, sensitive, ui_grantable)
SELECT gen_random_uuid(), v.key, v.module_key, v.resource, v.action, v.description, v.cerbos_kind, v.cerbos_action, v.class, v.sensitive, v.ui_grantable
FROM (VALUES
  ('hr.payroll.approve', 'hr', 'payroll', 'approve',
   'Approve a payroll run, a compensation change or a separation payout. Commits '
   'money; high-assurance only.',
   'hr_payroll', 'approve', 'grantable', true, true),
  ('hr.payroll.create', 'hr', 'payroll', 'create',
   'Create compensation records, allowances, benefit enrolments, payroll runs '
   'and separations.',
   'hr_payroll', 'create', 'grantable', true, true),
  ('hr.payroll.delete', 'hr', 'payroll', 'delete',
   'Delete or void payroll and compensation records.',
   'hr_payroll', 'delete', 'grantable', true, true),
  ('hr.payroll.export', 'hr', 'payroll', 'export',
   'Export the payroll register or bank file. High-assurance only.',
   'hr_payroll', 'export', 'grantable', true, true),
  ('hr.payroll.read', 'hr', 'payroll', 'read',
   'Read compensation records, allowances, benefit enrolments, tax profiles, '
   'payroll runs, payslips and separations.',
   'hr_payroll', 'read', 'grantable', true, true),
  ('hr.payroll.update', 'hr', 'payroll', 'update',
   'Amend compensation, recalculate a payroll run, edit a separation.',
   'hr_payroll', 'update', 'grantable', true, true),
  ('hr.policy.create', 'hr', 'policy', 'create',
   'Create HR configuration objects (leave policy, holiday calendar, review '
   'cycle, pay grade, statutory parameter set).',
   'hr_policy', 'create', 'grantable', true, true),
  ('hr.policy.delete', 'hr', 'policy', 'delete',
   'Remove an HR configuration object.',
   'hr_policy', 'delete', 'grantable', true, true),
  ('hr.policy.ratify', 'hr', 'policy', 'ratify',
   'Sign off a statutory parameter set as legally verified, unblocking payroll '
   'finalization against it.',
   'hr_policy', 'ratify', 'grantable', true, true),
  ('hr.policy.read', 'hr', 'policy', 'read',
   'Read HR configuration: holiday calendars, leave policies, review cycles, '
   'pay-grade structure, statutory parameter sets.',
   'hr_policy', 'read', 'grantable', false, true),
  ('hr.policy.update', 'hr', 'policy', 'update',
   'Amend HR configuration objects.',
   'hr_policy', 'update', 'grantable', true, true),
  ('hr.recruitment.approve', 'hr', 'recruitment', 'approve',
   'Approve a requisition or an offer. Commits headcount and money; '
   'high-assurance only.',
   'hr_recruitment', 'approve', 'grantable', true, true),
  ('hr.recruitment.convert', 'hr', 'recruitment', 'convert',
   'Convert an accepted offer into an employee record. The moment an outsider '
   'becomes staff; high-assurance only.',
   'hr_recruitment', 'convert', 'grantable', true, true),
  ('hr.recruitment.create', 'hr', 'recruitment', 'create',
   'Create requisitions, candidates, applications, interviews, scorecards and '
   'offers.',
   'hr_recruitment', 'create', 'grantable', true, true),
  ('hr.recruitment.delete', 'hr', 'recruitment', 'delete',
   'Delete recruitment records, including purging a candidate on an erasure '
   'request.',
   'hr_recruitment', 'delete', 'grantable', true, true),
  ('hr.recruitment.export', 'hr', 'recruitment', 'export',
   'Bulk-export the candidate pool. Outsider personal data; high-assurance only.',
   'hr_recruitment', 'export', 'grantable', true, true),
  ('hr.recruitment.read', 'hr', 'recruitment', 'read',
   'Read requisitions, candidates, applications, interviews and scorecards.',
   'hr_recruitment', 'read', 'grantable', true, true),
  ('hr.recruitment.update', 'hr', 'recruitment', 'update',
   'Advance an application, edit a requisition, reschedule an interview.',
   'hr_recruitment', 'update', 'grantable', true, true)
) AS v(key, module_key, resource, action, description, cerbos_kind, cerbos_action, class, sensitive, ui_grantable)
ON CONFLICT (key) DO UPDATE SET
  module_key = EXCLUDED.module_key, resource = EXCLUDED.resource, action = EXCLUDED.action,
  description = EXCLUDED.description, cerbos_kind = EXCLUDED.cerbos_kind,
  cerbos_action = EXCLUDED.cerbos_action, class = EXCLUDED.class,
  sensitive = EXCLUDED.sensitive, ui_grantable = EXCLUDED.ui_grantable;

-- ══════════════════════════════════════════════════════════════════════════════════════════════════
-- 2 · Role bundles, for the five role-arm roles only.
--
--     Note what hr_staff does and does not get: hr.policy.read and hr.recruitment.read, and nothing
--     else. Reading the leave policy is hr_staff-shaped work; rewriting it is not, and neither is
--     anything at all in hr_payroll.
--
--     Note also that hr.policy.ratify reaches company_admin/platform_admin/owner but NOT hr_manager.
--     Ratification declares the statutory numbers verified and unblocks payroll finalization
--     against them; it is an accountability act, not an HR-operations one.
-- ══════════════════════════════════════════════════════════════════════════════════════════════════
INSERT INTO role_permissions (role_id, permission_id, self_scoped)
SELECT r.id, p.id, bundle.self_scoped
FROM (VALUES
  ('member', 'hr.payroll.read', true),
  ('member', 'hr.policy.read', false),
  ('member', 'hr.recruitment.create', true),
  ('member', 'hr.recruitment.read', true),
  ('member', 'hr.recruitment.update', true),
  ('hr_staff', 'hr.policy.read', false),
  ('hr_staff', 'hr.recruitment.read', false),
  ('hr_manager', 'hr.payroll.approve', false),
  ('hr_manager', 'hr.payroll.create', false),
  ('hr_manager', 'hr.payroll.delete', false),
  ('hr_manager', 'hr.payroll.export', false),
  ('hr_manager', 'hr.payroll.read', false),
  ('hr_manager', 'hr.payroll.update', false),
  ('hr_manager', 'hr.policy.create', false),
  ('hr_manager', 'hr.policy.delete', false),
  ('hr_manager', 'hr.policy.read', false),
  ('hr_manager', 'hr.policy.update', false),
  ('hr_manager', 'hr.recruitment.approve', false),
  ('hr_manager', 'hr.recruitment.convert', false),
  ('hr_manager', 'hr.recruitment.create', false),
  ('hr_manager', 'hr.recruitment.delete', false),
  ('hr_manager', 'hr.recruitment.export', false),
  ('hr_manager', 'hr.recruitment.read', false),
  ('hr_manager', 'hr.recruitment.update', false),
  ('company_admin', 'hr.payroll.approve', false),
  ('company_admin', 'hr.payroll.create', false),
  ('company_admin', 'hr.payroll.delete', false),
  ('company_admin', 'hr.payroll.export', false),
  ('company_admin', 'hr.payroll.read', false),
  ('company_admin', 'hr.payroll.update', false),
  ('company_admin', 'hr.policy.create', false),
  ('company_admin', 'hr.policy.delete', false),
  ('company_admin', 'hr.policy.ratify', false),
  ('company_admin', 'hr.policy.read', false),
  ('company_admin', 'hr.policy.update', false),
  ('company_admin', 'hr.recruitment.approve', false),
  ('company_admin', 'hr.recruitment.convert', false),
  ('company_admin', 'hr.recruitment.create', false),
  ('company_admin', 'hr.recruitment.delete', false),
  ('company_admin', 'hr.recruitment.export', false),
  ('company_admin', 'hr.recruitment.read', false),
  ('company_admin', 'hr.recruitment.update', false),
  ('platform_admin', 'hr.payroll.approve', false),
  ('platform_admin', 'hr.payroll.create', false),
  ('platform_admin', 'hr.payroll.delete', false),
  ('platform_admin', 'hr.payroll.export', false),
  ('platform_admin', 'hr.payroll.read', false),
  ('platform_admin', 'hr.payroll.update', false),
  ('platform_admin', 'hr.policy.create', false),
  ('platform_admin', 'hr.policy.delete', false),
  ('platform_admin', 'hr.policy.ratify', false),
  ('platform_admin', 'hr.policy.read', false),
  ('platform_admin', 'hr.policy.update', false),
  ('platform_admin', 'hr.recruitment.approve', false),
  ('platform_admin', 'hr.recruitment.convert', false),
  ('platform_admin', 'hr.recruitment.create', false),
  ('platform_admin', 'hr.recruitment.delete', false),
  ('platform_admin', 'hr.recruitment.export', false),
  ('platform_admin', 'hr.recruitment.read', false),
  ('platform_admin', 'hr.recruitment.update', false),
  ('owner', 'hr.payroll.approve', false),
  ('owner', 'hr.payroll.create', false),
  ('owner', 'hr.payroll.delete', false),
  ('owner', 'hr.payroll.export', false),
  ('owner', 'hr.payroll.read', false),
  ('owner', 'hr.payroll.update', false),
  ('owner', 'hr.policy.create', false),
  ('owner', 'hr.policy.delete', false),
  ('owner', 'hr.policy.ratify', false),
  ('owner', 'hr.policy.read', false),
  ('owner', 'hr.policy.update', false),
  ('owner', 'hr.recruitment.approve', false),
  ('owner', 'hr.recruitment.convert', false),
  ('owner', 'hr.recruitment.create', false),
  ('owner', 'hr.recruitment.delete', false),
  ('owner', 'hr.recruitment.export', false),
  ('owner', 'hr.recruitment.read', false),
  ('owner', 'hr.recruitment.update', false)
) AS bundle(role_name, perm_key, self_scoped)
JOIN roles r ON r.company_id IS NULL AND r.name = bundle.role_name
JOIN permissions p ON p.key = bundle.perm_key
ON CONFLICT (role_id, permission_id) DO UPDATE SET self_scoped = EXCLUDED.self_scoped;

-- ══════════════════════════════════════════════════════════════════════════════════════════════════
-- 3 · Self-check. FLOORS rather than equalities where later growth is legitimate — an exact
--     tripwire fires on correct growth, which this program has hit as a false alarm several times.
--     The two invariants that are NOT floors (owner == company_admin, member == 0) are the two the
--     header argues for, and they are meant to break loudly if reversed.
-- ══════════════════════════════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  n_perm   integer;
  n_bundle integer;
  n_owner  integer;
  n_ca     integer;
  n_member integer;
  n_ratify integer;
BEGIN
  SELECT count(*) INTO n_perm FROM permissions
   WHERE key LIKE 'hr.policy.%' OR key LIKE 'hr.recruitment.%' OR key LIKE 'hr.payroll.%';
  IF n_perm <> 18 THEN
    RAISE EXCEPTION 'HR-FULL: expected 18 new HR permissions, found %', n_perm;
  END IF;

  SELECT count(*) INTO n_bundle FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
   WHERE p.key LIKE 'hr.policy.%' OR p.key LIKE 'hr.recruitment.%' OR p.key LIKE 'hr.payroll.%';
  IF n_bundle < 78 THEN
    RAISE EXCEPTION 'HR-FULL: expected at least 78 bundle rows, found %', n_bundle;
  END IF;

  SELECT count(*) INTO n_owner FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'owner'
     AND (p.key LIKE 'hr.policy.%' OR p.key LIKE 'hr.recruitment.%' OR p.key LIKE 'hr.payroll.%');
  SELECT count(*) INTO n_ca FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'company_admin'
     AND (p.key LIKE 'hr.policy.%' OR p.key LIKE 'hr.recruitment.%' OR p.key LIKE 'hr.payroll.%');
  IF n_owner <> n_ca THEN
    RAISE EXCEPTION 'HR-FULL: owner holds % of the new HR keys, company_admin holds % — they must match (owner-role.db.test.ts)', n_owner, n_ca;
  END IF;

  -- `member` holds exactly the self/panel-scoped keys and NOTHING that only staff can reach. This
  -- is the assertion that would catch a future mirror widening member's reach: an approve, a
  -- convert, an export or a delete arriving in member's bundle is the failure mode, not a read.
  SELECT count(*) INTO n_member FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'member'
     AND p.key IN ('hr.policy.create','hr.policy.update','hr.policy.delete','hr.policy.ratify',
                   'hr.recruitment.approve','hr.recruitment.convert','hr.recruitment.export','hr.recruitment.delete',
                   'hr.payroll.create','hr.payroll.update','hr.payroll.delete','hr.payroll.approve','hr.payroll.export');
  IF n_member <> 0 THEN
    RAISE EXCEPTION 'HR-FULL: member holds % staff-only HR key(s) — a self/panel-scoped rule must never widen into one', n_member;
  END IF;

  SELECT count(*) INTO n_ratify FROM role_permissions rp
    JOIN permissions p ON p.id = rp.permission_id
    JOIN roles r ON r.id = rp.role_id
   WHERE r.company_id IS NULL AND r.name = 'hr_manager' AND p.key = 'hr.policy.ratify';
  IF n_ratify <> 0 THEN
    RAISE EXCEPTION 'HR-FULL: hr_manager must NOT hold hr.policy.ratify, found % row(s)', n_ratify;
  END IF;
END $$;
