// WSK-20 — §06: "the generated conformance test (compile-time: SDK types satisfy every referenced
// block/collection; runtime probe: each referenced collection returns the /v1 envelope against the
// target env)". Generated as a STRING; this scaffolder never runs it (WSK-D6) — repo CI does
// (qa-harness-workflow.ts wires the job that runs it).
export function generateConformanceTest(args: {
  tenantSlug: string;
  referencedCollections: string[];
  blockTypesUsed: string[];
}): string {
  const { tenantSlug, referencedCollections, blockTypesUsed } = args;
  return `// GENERATED by code.scaffold v2 (WSK-20) — conformance test. Runs in repo CI / Zone B previews
// ONLY; the agent-runner that generated this file never executes it (webdesk-design.md §06, WSK-D6).
import { describe, it, expect } from "vitest";
import type { paths } from "@gaiada/webdesk-sdk";
import { BLOCK_TYPE_NAMES, isBlockType } from "@gaiada/webdesk-blocks";

const REFERENCED_COLLECTIONS = ${JSON.stringify(referencedCollections)} as const;
const BLOCK_TYPES_USED = ${JSON.stringify(blockTypesUsed)} as const;
const TENANT_SLUG = ${JSON.stringify(tenantSlug)};

describe("contract conformance (compile-time)", () => {
  it("every referenced block type is still in the installed block library's known set", () => {
    for (const t of BLOCK_TYPES_USED) {
      expect(BLOCK_TYPE_NAMES.includes(t as (typeof BLOCK_TYPE_NAMES)[number])).toBe(true);
      expect(isBlockType(t)).toBe(true);
    }
  });

  it("the installed SDK's path types cover every referenced collection", () => {
    // Compile-time: if a referenced collection's list/item path were missing from the installed
    // \`paths\` type, this file would fail to type-check in repo CI — the check IS the \`tsc\`/\`astro
    // check\` step in qa-harness.yml, not a runtime assertion (there is nothing to assert at runtime
    // about a TYPE). Referenced here so an unused-import lint can never silently drop the guard.
    type _ListPath = paths[\`/v1/t/\${typeof TENANT_SLUG}/\${(typeof REFERENCED_COLLECTIONS)[number]}\`];
    type _ItemPath = paths[\`/v1/t/\${typeof TENANT_SLUG}/\${(typeof REFERENCED_COLLECTIONS)[number]}/{slug}\`];
    expect(REFERENCED_COLLECTIONS.length).toBeGreaterThanOrEqual(0);
  });
});

describe("contract conformance (runtime probe)", () => {
  const host = process.env.WEBDESK_TEST_TARGET_HOST;
  const apiKey = process.env.WEBDESK_TEST_API_KEY ?? "";

  it.skipIf(!host)("every referenced collection returns the /v1 envelope shape", async () => {
    for (const collection of REFERENCED_COLLECTIONS) {
      const res = await fetch(\`https://\${host}/v1/t/\${TENANT_SLUG}/\${collection}\`, {
        headers: { Authorization: \`Bearer \${apiKey}\` },
      });
      expect(res.ok).toBe(true);
      const body = (await res.json()) as { collection?: string; items?: unknown[]; page?: unknown };
      expect(body.collection).toBe(collection);
      expect(Array.isArray(body.items)).toBe(true);
      expect(body.page).toBeDefined();
    }
  });
});
`;
}

export function conformanceTestFilePath(): string {
  return "src/__generated__/contract-conformance.test.ts";
}
