// WSK-20 — turns a PrototypeSpec into generated repo pages, composed exclusively from
// `@gaiada/webdesk-blocks` components fed by the ONE typed SDK client (sdk-client-template.ts).
//
// SITE-KIND INTERPRETATION (§06 leaves this open — reported): `astro` and `node` are both built on
// the SAME Astro block-renderer library (webdesk/blocks, WSK-16, `peerDependencies: astro` — it has
// no non-Astro build), which is the only installable block library this rail has (§06/§05 Layer 1).
// This ticket reads "astro" siteKind as a fully static build (`output: 'static'`) and "node" siteKind
// as the SAME Astro pages built for SSR via `@astrojs/node` (`output: 'server'`) — i.e. the two
// differ only in astro.config.mjs's output/adapter (templates/astro-site.ts,
// templates/node-site.ts), never in how a page is composed. This is a documented assumption, not a
// frozen decision — flagged for architect confirmation in the ticket's report.
import type { VocabularyGap } from "./envelope";
import type { CollectionIndex } from "./openapi-index";
import { collectionExists } from "./openapi-index";
import type { PrototypePageSpec, PrototypeSpec } from "./prototype-spec";
import { buildSchemaProposalDraft, schemaProposalFilePath, todoStubFilePathAstro } from "./schema-gap";

export interface GeneratedFile {
  path: string;
  /** A Buffer only for vendored binary artifacts (git-writer.ts's `vendorFiles` — the SDK/block
   *  tarballs); every page-composer output is a string. */
  content: string | Buffer;
}

export interface ComposeResult {
  files: GeneratedFile[];
  gaps: VocabularyGap[];
  /** Every collection a generated (non-gap) page actually referenced — the conformance test's
   *  runtime-probe list (§06: "each referenced collection returns the /v1 envelope"). */
  referencedCollections: string[];
}

function routePath(slug: string): string {
  return slug === "" ? "index" : slug;
}

function staticPlaceholderPage(page: PrototypePageSpec): GeneratedFile {
  // No collection bound — an honestly static page (§06 hard rule: never invent an SDK call this
  // page has no real data source for). Hero + Cta cover the "landing page" shape without guessing
  // content the prototype never specified.
  const content = `---
// GENERATED by code.scaffold v2 (WSK-20) — static page, no bound collection.
import { Hero, Cta } from "@gaiada/webdesk-blocks";
---
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(page.title)}</title>
  </head>
  <body>
    <Hero heading=${JSON.stringify(page.title)} />
    <!-- TODO(webdesk): replace this placeholder Cta once real content/composition exists for this page. -->
    <Cta heading="Get in touch" buttonLabel="Contact us" buttonHref="/contact" />
  </body>
</html>
`;
  return { path: `src/pages/${routePath(page.slug)}.astro`, content };
}

function itemPage(page: PrototypePageSpec, collection: string): GeneratedFile {
  const content = `---
// GENERATED by code.scaffold v2 (WSK-20) — item page bound to collection "${collection}".
import { ItemRenderer, DraftBanner, LocaleFallbackNotice } from "@gaiada/webdesk-blocks";
import { getItem } from "../lib/webdesk-sdk";

const { slug } = Astro.params;
const envelope = await getItem(${JSON.stringify(collection)}, String(slug));
---
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{envelope.seo?.title ?? ${JSON.stringify(page.title)}}</title>
  </head>
  <body>
    {envelope.meta?.draft && <DraftBanner />}
    {envelope.meta?.x?.localeFallback && <LocaleFallbackNotice fallback={envelope.meta.x.localeFallback} />}
    <ItemRenderer envelope={envelope} />
  </body>
</html>
`;
  return { path: `src/pages/${routePath(page.slug)}/[slug].astro`, content };
}

function listingPage(page: PrototypePageSpec, collection: string): GeneratedFile {
  const content = `---
// GENERATED by code.scaffold v2 (WSK-20) — listing page for collection "${collection}".
import { listItems } from "../lib/webdesk-sdk";

const list = await listItems(${JSON.stringify(collection)});
---
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(page.title)}</title>
  </head>
  <body>
    <h1>${escapeHtml(page.title)}</h1>
    <ul>
      {list.items.map((item: { slug: string; seo?: { title?: string } }) => (
        <li><a href={\`/${routePath(page.slug)}/\${item.slug}\`}>{item.seo?.title ?? item.slug}</a></li>
      ))}
    </ul>
  </body>
</html>
`;
  return { path: `src/pages/${routePath(page.slug)}.astro`, content };
}

function todoGapPage(page: PrototypePageSpec, reference: string, kind: "unknown-collection" | "unknown-block-type"): GeneratedFile {
  const content = `---
// GENERATED by code.scaffold v2 (WSK-20) — VOCABULARY GAP.
// The prototype's page "${page.title}" (slug: "${page.slug}") references ${kind} "${reference}",
// which the pinned contract snapshot does not have. Per webdesk-design.md §06, this is NEVER filled
// in with a hand-rolled fetch — a schema-proposal draft was written alongside this file
// (see ${schemaProposalFilePath({ kind, reference })}); a human reviews and submits it via the
// console's schema-propose flow (WSK-32) before this page can be finished.
---
<html lang="en">
  <head><meta charset="utf-8" /><title>TODO — ${escapeHtml(page.title)}</title></head>
  <body>
    <!-- TODO(webdesk): unresolved ${kind} "${reference}" — see the schema-proposal draft. -->
    <p>This page is pending a vocabulary/composition change (${escapeHtml(reference)}).</p>
  </body>
</html>
`;
  return { path: todoStubFilePathAstro(page.slug), content };
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function composePages(spec: PrototypeSpec, index: CollectionIndex): ComposeResult {
  const files: GeneratedFile[] = [];
  const gaps: VocabularyGap[] = [];
  const referenced = new Set<string>();

  for (const page of spec.pages) {
    if (!page.collection) {
      files.push(staticPlaceholderPage(page));
      continue;
    }
    if (!collectionExists(index, page.collection)) {
      const gap: VocabularyGap = {
        pageSlug: page.slug,
        kind: "unknown-collection",
        reference: page.collection,
        todoFilePath: todoStubFilePathAstro(page.slug),
        proposalFilePath: schemaProposalFilePath({ kind: "unknown-collection", reference: page.collection }),
      };
      gaps.push(gap);
      files.push(todoGapPage(page, page.collection, "unknown-collection"));
      files.push({
        path: gap.proposalFilePath,
        content: JSON.stringify(buildSchemaProposalDraft({ pageSlug: page.slug, kind: "unknown-collection", reference: page.collection }), null, 2) + "\n",
      });
      continue;
    }
    referenced.add(page.collection);
    files.push(page.isListing ? listingPage(page, page.collection) : itemPage(page, page.collection));
  }

  return { files, gaps, referencedCollections: [...referenced].sort() };
}
