// WSK-20 — §06: "the QA-harness CI workflow pre-wired (a stub until webdev P5 ships the harness —
// the workflow file + signed-webhook target land now so the harness drops in without a repo change)".
//
// Target naming follows the existing B->A signed-webhook precedent (`wd-zoneb-intake`,
// webdesk-design.md §03 B->A channel 1) and webdev-design.md §12's own `wd-qa-intake` line ("repo-CI
// signed webhook... the scaffolder pre-wires the repo side (WSK-20)") — this ticket's OWN proposed
// secret/env names (`QA_HARNESS_WEBHOOK_URL`/`QA_HARNESS_WEBHOOK_SECRET`), not a confirmed webdev-P5
// contract; the receiving endpoint does not exist yet (webdev P5, unbuilt). The workflow runs the
// generated conformance test and posts a signed result unconditionally — the harness itself (real
// per-block/per-page checks beyond conformance) is P5's own addition, dropped in as extra steps with
// no repo change to this file's secrets/target wiring, per §06.
export function generateQaHarnessWorkflow(args: { webdeskTestTargetHostEnvVar?: string }): string {
  const hostVar = args.webdeskTestTargetHostEnvVar ?? "WEBDESK_TEST_TARGET_HOST";
  return `# GENERATED by code.scaffold v2 (WSK-20). STUB pending webdev P5's real QA harness (\`wd-qa-intake\`).
# The conformance test + signed-webhook POST below are real; the per-block/per-page harness checks
# themselves are P5's addition — they drop into the "run harness" step with no change to this file's
# secrets or target wiring (webdesk-design.md §06).
name: qa-harness

on:
  push:
    branches: [main]
  pull_request:

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      # The actual compile gate ("a repo that compiles" — §06's acceptance bar). The scaffolder itself
      # never runs this (WSK-D6) — repo CI is the first place it ever runs at all.
      - run: npm run build
      - run: npm run test
        env:
          ${hostVar}: \${{ vars.WEBDESK_STAGING_HOST }}
          WEBDESK_TEST_API_KEY: \${{ secrets.WEBDESK_STAGING_API_KEY }}
      # TODO(webdev P5): the real QA harness runs here (block/page-level checks). Until it lands,
      # this stub reports the conformance-test result only.
      - name: report to wd-qa-intake (signed)
        if: always()
        env:
          QA_HARNESS_WEBHOOK_URL: \${{ secrets.QA_HARNESS_WEBHOOK_URL }}
          QA_HARNESS_WEBHOOK_SECRET: \${{ secrets.QA_HARNESS_WEBHOOK_SECRET }}
        run: |
          if [ -z "$QA_HARNESS_WEBHOOK_URL" ]; then
            echo "QA_HARNESS_WEBHOOK_URL not set — wd-qa-intake is not live yet (webdev P5). Skipping report."
            exit 0
          fi
          PAYLOAD='{"runId":"'"$GITHUB_RUN_ID"'","sha":"'"$GITHUB_SHA"'","status":"'"$JOB_STATUS"'"}'
          SIG=$(printf '%s' "$PAYLOAD" | openssl dgst -sha256 -hmac "$QA_HARNESS_WEBHOOK_SECRET" | sed 's/^.* //')
          curl -sf -X POST "$QA_HARNESS_WEBHOOK_URL" \\
            -H "Content-Type: application/json" \\
            -H "X-Signature: sha256=$SIG" \\
            -d "$PAYLOAD"
        continue-on-error: true
`;
}

export function qaHarnessWorkflowFilePath(): string {
  return ".github/workflows/qa-harness.yml";
}
