// WSK-20 — §06: "vocabulary gaps -> flagged TODO + a proposeSchema draft, never hand-rolled fetch
// code". WSK-32 (`webdesk.schema.propose`, LOW write, draft-only by construction per §07's MCP tool
// table) is UNBUILT as of this ticket (PROGRESS.md: ⬜). This file defines the draft's shape as a
// PLAIN FILE the scaffolder writes into the repo — it never calls the (nonexistent) tool itself; a
// human/reviewer applies the draft through WS4 once WSK-32 ships. The shape mirrors §05 Layer 2's
// composition-as-data convention (`collections.schema` = `{fields?, blocks?}`, WSK-14's de-facto
// reading) so the eventual `webdesk.schema.propose` input can be this file's content verbatim.
import type { VocabularyGap } from "./envelope";

export interface SchemaProposalDraft {
  kind: "unknown-collection" | "unknown-block-type";
  reference: string;
  requestedByPage: string;
  /** Best-effort composition sketch a human reviewer edits before submitting — NEVER auto-applied. */
  suggestedComposition: { fields?: unknown[]; blocks?: unknown[] };
  note: string;
}

export function buildSchemaProposalDraft(gap: {
  pageSlug: string;
  kind: "unknown-collection" | "unknown-block-type";
  reference: string;
}): SchemaProposalDraft {
  return {
    kind: gap.kind,
    reference: gap.reference,
    requestedByPage: gap.pageSlug,
    suggestedComposition: gap.kind === "unknown-collection" ? { fields: [], blocks: [] } : { blocks: [] },
    note:
      "DRAFT ONLY — generated by code.scaffold v2 (WSK-20). This is not applied: a human reviews and " +
      "submits it via the console's schema-propose flow (webdesk-design.md §06/§07, webdesk.schema.propose, " +
      "WSK-32) before it becomes a real composition change. Never auto-applied by this scaffolder.",
  };
}

export function schemaProposalFilePath(gap: { kind: "unknown-collection" | "unknown-block-type"; reference: string }): string {
  const safe = gap.reference.replace(/[^a-zA-Z0-9-_]+/g, "-");
  return `webdesk-schema-proposals/${gap.kind}-${safe}.json`;
}

export function todoStubFilePathAstro(pageSlug: string): string {
  const route = pageSlug === "" ? "index" : pageSlug;
  return `src/pages/${route}.astro`;
}

export function todoStubFilePathNode(pageSlug: string): string {
  const route = pageSlug === "" ? "index" : pageSlug;
  return `src/routes/${route}.ts`;
}
