// WSK-20 — the ONE central data-access module every generated page imports. §06: "pages composed
// exclusively from block-library components fed by typed SDK calls... never hand-rolled fetch code".
// The installed `sdk.ts.tgz` (from the pinned snapshot, WSK-15/WSK-D19) is `openapi-typescript`
// OUTPUT — TYPES ONLY (`paths`/`components["schemas"]`), not a callable client (confirmed reading
// webdesk/api/src/codegen/generator/sdk-ts.mts: `openapiTS(doc) -> astToString(ast)`, no runtime
// export). So the "typed SDK call" a page makes is: import the installed types, call through THIS ONE
// generated fetch wrapper (authored once, here, by the scaffolder — never per-page), typed against
// them. This is composed as a STRING TEMPLATE; the scaffolder never imports or executes it —
// generated code that runs in repo CI / Zone B previews, per WSK-D6.
export function generateSdkClientModule(args: { tenantSlug: string; envelopeVersion?: string }): string {
  const { tenantSlug } = args;
  return `// GENERATED by code.scaffold v2 (WSK-20) — the repo's ONE typed data-access module.
// Do not hand-roll a second fetch call anywhere else in this repo; every page imports from here.
// Types come from the installed, snapshot-pinned SDK package (see CONTRACT.lock at repo root).
import type { paths } from "@gaiada/webdesk-sdk";

const HOST = process.env.WEBDESK_HOST ?? "";
const TENANT_SLUG = ${JSON.stringify(tenantSlug)};
const API_KEY = process.env.WEBDESK_API_KEY ?? "";

export class WebdeskFetchError extends Error {
  constructor(public status: number, public detail: string) {
    super(\`webdesk fetch failed: \${status} \${detail}\`);
    this.name = "WebdeskFetchError";
  }
}

async function request<T>(path: string, params: Record<string, string | undefined> = {}): Promise<T> {
  if (!HOST) throw new Error("WEBDESK_HOST is not set");
  const url = new URL(\`https://\${HOST}\${path}\`);
  for (const [k, v] of Object.entries(params)) if (v !== undefined) url.searchParams.set(k, v);
  const res = await fetch(url, { headers: { Authorization: \`Bearer \${API_KEY}\` } });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new WebdeskFetchError(res.status, body.slice(0, 500));
  }
  return (await res.json()) as T;
}

/** GET /v1/t/{tenantSlug}/{collection} — typed against the installed SDK's ListEnvelope shape. */
export function listItems<T = unknown>(
  collection: string,
  opts: { locale?: string; cursor?: string; limit?: number; expandBlocks?: boolean } = {},
): Promise<T> {
  type _ListPaths = paths[\`/v1/t/\${typeof TENANT_SLUG}/\${string}\`];
  return request<T>(\`/v1/t/\${TENANT_SLUG}/\${collection}\`, {
    locale: opts.locale,
    cursor: opts.cursor,
    limit: opts.limit?.toString(),
    expand: opts.expandBlocks ? "blocks" : undefined,
  });
}

/** GET /v1/t/{tenantSlug}/{collection}/{slug} — typed against the installed SDK's ItemEnvelope shape. */
export function getItem<T = unknown>(collection: string, slug: string, opts: { locale?: string } = {}): Promise<T> {
  return request<T>(\`/v1/t/\${TENANT_SLUG}/\${collection}/\${slug}\`, { locale: opts.locale });
}

/** GET /v1/t/{tenantSlug}/search */
export function search<T = unknown>(q: string, opts: { collection?: string; locale?: string; cursor?: string; limit?: number } = {}): Promise<T> {
  return request<T>(\`/v1/t/\${TENANT_SLUG}/search\`, { q, collection: opts.collection, locale: opts.locale, cursor: opts.cursor, limit: opts.limit?.toString() });
}
`;
}
